### ISSUE TITLE
upmpdcli won't play some audio broadcast from minimserver

### ISSUE THREAD

**Issue by Pastim** [medoc92/upmpdcli#10]
Hi,

I am using minimserver (on one system) via upplay to upmpdcli and mpd (these 3 all on one PC).  

I can play normal tracks without issue.  However, the BBC are now broadcasting radio in a new format, via m3u8 files.  minimserver (with ministreamer) services this as wav files with no problem to other UPnP devices on my network using upplay.  However, to upmpdcli I get no sound.  It has an error 'found object of unknown class' - see below.

src/avtransport.cxx:307::Set(next)AVTransportURI: next 0 uri http://192.168.1.10:9790/minimstreamer/*/R2/http/a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high/ak/bbc_radio_two.m3u8/$!transcode.wav metadata[<?xml version="1.0" encoding="utf-8"?><DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/"><item id="0$playlists$*p1$*c2" parentID="0$playlists$*p1" restricted="1"><dc:title>[R2] BBC Radio 2</dc:title><res protocolInfo="http-get:*:audio/x-wav:*">http://192.168.1.10:9790/minimstreamer/*/R2/http/a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high/ak/bbc_radio_two.m3u8/$!transcode.wav</res><upnp:class>object.item.audioItem.audioBroadcast</upnp:class></item></DIDL-Lite>]
src/mpdcli.cxx:560::MPDCli::clearQueue 
libupnpp/control/cdircontent.cxx:108::checkobjok: found object of unknown class: [object.item.audioItem.audioBroadcast]
src/mpdcli.cxx:508::MPDCli::insert at :0 uri http://192.168.1.10:9790/minimstreamer/*/R2/http/a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/uk/sbr_high/ak/bbc_radio_two.m3u8/$!transcode.wav
src/mpdcli.cxx:384::MPDCli::play(pos=0)
src/mpdcli.cxx:405::MPDCli::stop
libupnpp/device/device.cxx:288::UPNP_CONTROL_ACTION_REQUEST: Play. Params: <?xml version="1.0"?>
<u:Play xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
<InstanceID>0</InstanceID>
<Speed>1</Speed>
</u:Play>

**Comment by Pastim** [comment]
A new version of minimstreamer has been released this afternoon that fixes the problem by sending out a normal 'aac' stream.  I'm not 100% sure that there is no issue in upmpdcli, but even if there is it doesn't affect me any more.

I'll leave this open until someone has read it - it can then be closed as far as I'm concerned.

**Comment by medoc92** [comment]
Hi,

What MPD version are you using ? I think that this has a better chance to be related to MPD's general distaste for playing wav over http than to the "object of unknown class" thing. I think that the latter is mostly informational, but I'd have to test to be sure.

**Comment by Pastim** [comment]
I am still converting to wav and it now works, so I'm not sure what you are referring to.  Can you clarify what the problem is there?

My mpd says it is "v0.19.8-312-g4c74016"

I can't test this any more because minimstreamer has changed the way it delivers the audio to be closer to aac, albeit still converted to wav.

**Comment by medoc92** [comment]
mpd 0.18 had major issues for playing wav files fetched trough HTTP (this is what happens when using an UPnP frontend). The problems are largely but not completely solved in 0.19, and in my experience, things work better (or only work)  if only libsndfile is configured in, and libaudiofile is excluded. For example, 24 bits audio from upmpdcli+Songcast only works with mpd 0.19 using libsndfile only.

I am not too sure of what you mean with "closer to aac but still converted to wav". Do you mean that this is a wav-encapsulated aac stream ? Some of the problems with wavs depended on the actual bitrate, so it might be conceivable that encapsulating a compressed format could change the problem.

**Comment by Pastim** [comment]
The underlying BBC audio stream, when you get to the bottom of a long pile of m3us etc, is aac.  As I understand it (somewhat dimly) the newer version of minimstreamer declares this explicitly, delivering a file with an aac extension, whereas the previous version did not do so, delivering a file with an m3u8 extension followed by a wav extension.

It seems OK now so I'll close this - is that alright?
