### ISSUE TITLE
[Enhancement] Support redirected radio

### ISSUE THREAD

**Issue by parkmino** [medoc92/upmpdcli#105]
I'd like to play the radio with redirected url e.g. http://juoradio.appspot.com/kbs1.
The following command extract the redirected url which is constantly changing.

curl -X GET -I http://juoradio.appspot.com/kbs1 | grep -i '^Location:' | cut -d ' ' -f2
=> mms://kong.kbs.gscdn.com/1fm?...

Thanks in advance.

**Comment by medoc92** [comment]
I modified the radio url processing script to handle this. You can try it by replacing /usr/share/upmpdcli/rdpl2stream with the current git code for the directory.

**Comment by parkmino** [comment]
I rebuilt with the latest git and played 7 radios as above.
All works flawlessly and thanks a lot!
