### ISSUE TITLE
:2:libupnpp/upnpplib.cxx:149::UpnpInit :-208: UPNP_E_SOCKET_ERROR

### ISSUE THREAD

**Issue by Sufi-Al-Hussaini** [medoc92/upmpdcli#108]
Hello @medoc92,

This is very similar to #58, except that I'm getting the generic `UPNP_E_SOCKET_ERROR`.
It is worth mentioning that I'm running upmpdcli on embedded linux built using buildroot.

I believe your [comment](https://github.com/medoc92/upmpdcli/issues/58#issuecomment-254633928) on #58 that this problem has something to do with kernel parameters is spot-on. And I have tried changing a lot of stuff but haven't been able to solve this problem yet.

I was wondering if you had any specific kernel config options in mind.  

Thanks.

**Comment by joerg-krause** [comment]
Do you build your Linux kernel with Buildroot, too? Please check if CONFIG_IP_MULTICAST is enabled.

**Comment by Sufi-Al-Hussaini** [comment]
That is it! `CONFIG_IP_MULTICAST` is currently disabled. 
Thank you very much!
