### ISSUE TITLE
CurentURIMetaData compatibility issue

### ISSUE THREAD

**Issue by kappa8086** [medoc92/upmpdcli#109]
Since version 1.1.4 (probably), some bad implemented DMC apps have been failed to push media to upmpdcli, as I have seen this change in changelog:
```
Add content format compatibility checking. Can be disabled by setting checkcontentformat to 0
```
but even I set the config as described, it still denies to play some media those URL directly from internet, while upmpdcli log shows 
```
src/upmpd.cxx:132::checkContentFormat: didl parse failed
src/avtransport.cxx:393::set(Next)AVTransportURI: unsupported format: xxx ...
```
Apparently metadata is wrong or missing for these files.

On the other hand, these days I'm trying to write a DMC script with python, similar code like you can search that leaves CurrentURIMetaData tag empty, failed again with upmpdcli.
Thus, as far as I can see, metadata is ignored in a lot of simple solutions, but newer upmpdcli is not compatible for them.

Is it a BUG or a designed-to-be?

**Comment by medoc92** [comment]
I think that this is fixed by this commit: https://github.com/medoc92/upmpdcli/commit/e3d7b1566c027010d247ae403ecf1a444a2281fb

It will hopefully soon make its way in a released version...

**Comment by kappa8086** [comment]
Well updated, thx :)
