### ISSUE TITLE
MPD through DSP

### ISSUE THREAD

**Issue by arjunmenon** [medoc92/upmpdcli#112]
Hey
Is there a way to route the MPD first through a script running this [audio enhancement tool](https://github.com/zhangsu/seal), then to ALSA?

Visually, at present
phone -> mpd on pi -> alsa -> usb audio

required
phone -> mpd on pi -> script using `seal` gem -> alsa -> usb audio

Using a Pi 3 with USB DAC.

**Comment by medoc92** [comment]
Well this is really not an upmpdcli issue, but I guess that you could use the MPD FIFO output, to get the output through your tool, and then to ALSA. Please do not reopen, this has nothing to do with upmpdcli.
