### ISSUE TITLE
debs for rasbian stretch?

### ISSUE THREAD

**Issue by Locke** [medoc92/upmpdcli#113]
Hi,

I have upgraded my raspberry pi 3 running raspbian to debian 9 / stretch. That combination is not mentioned on https://www.lesbonscomptes.com/upmpdcli/downloads.html#debian.

Running the Raspbian Jessie version results in an immediate segfault. (I haven't saved the strace, if you're interested in it I could install that version again to report it to you. But I don't think we should care about that crash.)

So I changed `/etc/apt/sources.list.d/upmpdcli.list` to the Debian Stretch setting and build the package according to https://www.lesbonscomptes.com/upmpdcli/upmpdcli-debian-build.txt.

I couldn't install the mentioned `hardening-wrapper` package and had to install `dh-systemd`, but besides that everything seems to work perfectly.

Now to my question: do you plan to provide binary packages also for raspbian stretch? I think more people will be interested in them once the first official raspbian image with stretch is released (might take some time though).

**Comment by medoc92** [comment]
Thanks for pointing this out. I updated the downloads page to tell people to use the source package for raspbian stretch for now, and fixed the build sequence (adjusted the versions, hardening-wrapper, dh-systemd)

I'll wait for a Raspbian stretch image to provide the packages, I'm too lazy to do a jessie-to-stretch upgrade by hand...
