### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Pastim** [medoc92/upmpdcli#12]
I have been building this myself until now.  With the most recent version I get this error on the 'make install', having done the configure and make.  It's no problem for me, I'll get the ppa version instead.

Entering directory `/home/crusty/Programs/upmpdcli'
 /bin/mkdir -p '/usr/bin'
  /usr/bin/install -c upmpdcli scctl '/usr/bin'
 /bin/mkdir -p '/etc'
 /usr/bin/install -c -m 644 src/upmpdcli.conf '/etc'
 /bin/mkdir -p '/usr/share/upmpdcli'
 /usr/bin/install -c -m 644 src/description.xml src/AVTransport.xml src/RenderingControl.xml src/ConnectionManager.xml src/OHProduct.xml src/OHInfo.xml src/OHTime.xml src/OHVolume.xml src/OHPlaylist.xml src/OHReceiver.xml src/protocolinfo.txt src/presentation.html '/usr/share/upmpdcli'
 /bin/mkdir -p '/usr/share/man/man1'
 /usr/bin/install -c -m 644 man/upmpdcli.1 '/usr/share/man/man1'
make  install-data-hook
make[2]: Entering directory `/home/crusty/Programs/upmpdcli'
(cd /usr/share/upmpdcli; tar xzf -) < ./web.tar.gz 
/bin/bash: ./web.tar.gz: No such file or directory
make[2]: *** [install-data-hook] Error 1
make[2]: Leaving directory `/home/crusty/Programs/upmpdcli'
make[1]: *** [install-data-am] Error 2
make[1]: Leaving directory `/home/crusty/Programs/upmpdcli'
make: *** [install-am] Error 2

**Comment by medoc92** [comment]
Thanks for reporting this. 

I think that this only happens for out-of-tree builds (I can't reproduce the issue in-tree), I'll fix it. The workaround for now is to build in-tree.

The Ubuntu PPA is not yet updated, only the Debian packages.

In any case, updating to this release only makes sense if you want to play with multi-room Songcast, nothing much else changed.
 
Cheers,

jf

**Comment by Pastim** [comment]
I started again with a fresh directory and all seems well now.  I'm not sure what 'out-of-tree' means (in English it has conotations of meaning drunk or crazed on drugs!), but whatever it was it's OK for me now.

I have this slightly stupid habit of trying to keep up to date, even if I don't need to :)

**Comment by medoc92** [comment]
Out of tree is something like this:

    tar xvzf upmpdcli-0.11.0.tar.gz  
    mkdir build
    cd build
    ../upmpdcli-0.11.0/configure --prefix=/usr
    make

It's useful when you want to build several architectures from the same source tree, and it's broken with the current tar distrib. Another way to trigger the problem was to run 'make clean' in the extracted tar directory. Maybe that's what you did.
