### ISSUE TITLE
No connection between sc2mpd and Linn

### ISSUE THREAD

**Issue by TripleEmcoder** [medoc92/upmpdcli#20]
I have installed upmpdcli and sc2mpd, but nothing shows up in Linn Songcast. Nothing interesting shows up in upmpdcli log on level 3, and no sc2mpd log is created. How can I check if upmpdcli is picking up sc2mpd? How can I verify that the Songcast capability is advertised?

**Comment by medoc92** [comment]
Does upmpdcli work normally apart from this ?
If sc2mpd is in /usr/bin (or somewhere else in the PATH), it should be picked up automatically.
You can check with upnp-insptector the Receiver service is offered by upmpdcli

Else you can try to toggle the unicast/multicast mode in the songcast preferences. Multicast often does not work on WIFI. But this should not affect the Receiver existence, just how it works.

**Comment by TripleEmcoder** [comment]
I can send files from Windows Media Player over UPnP to upmpdcli without issues and they are played with mpd.

I also verified that installing sc2mpd adds the Receiver interface:

>Methods	6
>Parent presentation URL	http://192.168.14.22:49154/upmpd/presentation.html
>Parent UDN	urn:schemas-upnp-org:device:MediaRenderer:1
>Service ID	urn:av-openhome-org:serviceId:Receiver
>Service URL	http://192.168.14.22:49154/upmpd/OHReceiver.xml
>State variables	4
>Version	1.0

So it seems that Linn is not able to discover the interface, as I get nothing shown on the list of receivers in Preferences.

I am running all of this over WiFi, true, but Windows Media Player does work without issues. Nothing happens when I change Unicast to Multicast or vice versa.

**Comment by medoc92** [comment]
What songcast version are you using. 

I guess you already tried this, but sometimes, restarting windows can get songcast out of a confused state.

**Comment by TripleEmcoder** [comment]
Linn Songcast 4.5.298 Davaar

Yes, I did try restarting both machines.

**Comment by medoc92** [comment]
Ok, I just gave a try to 4.5, and I can't get it to work (I do see the Receiver though, so not exactly the same problem you are seeing, It is just marked "unavailable").

4.4.190 seems to work fine for me, maybe you could give it a try ?
http://oss.linn.co.uk/Releases/Songcast/Davaar/

**Comment by TripleEmcoder** [comment]
Brilliant, that version detects the receiver and connects to it just fine.

Sounds seems ok in mpd mode, but is delayed by 10s - is that normal?

In alsa mode I get chops at regular intervals - is there a way to pass ALSA parameters to sc2mpd, like buffer/period size?

**Comment by medoc92** [comment]
Yes, there is a delay before the sound start in mpd mode, due to buffering.

You should not get chops in Alsa mode, that's the very purpose of the thing, it's supposed to adapt the rate of the incoming sample flow to the local clock, so that no buffer over- or under-flow occurs.

So, something is not working in your case. Probably the software is not detecting correctly the state of the  input buffer. You could try to set sc2mpd in debug mode (scloglevel), and see if you can see anything suspicious with tail -f. It normally reports what it sees in the buffer, and the resulting calculated sample rate ratio. The source code is in alsadirect.cpp.

**Comment by TripleEmcoder** [comment]
Thank you very much for your help and your explanations. I will go ahead and close this issue as I do have a working setup.
