### ISSUE TITLE
File Properties

### ISSUE THREAD

**Issue by rompolompo** [medoc92/upmpdcli#21]
Running the latest version of upmpdcli and mpd. When playing Hi-Res FLAC file, the file properties appears as "xxxxkbps | 192.0kHz". The xxxxx keep changing according to the bits per second. On a different renderer, it is shown as "FLAC | 192.0kHz | 24 bits". Any ideas? Thanks!

**Comment by medoc92** [comment]
I got your message on Disqus too by the way... Was a bit busy during/after the holidays.

MPD supplies 2 values with its status: kbit_rate, which can probably vary according to the data being currently decoded, and sample_rate, which is probably a static file attribute (feel free to check on these :) )

kbrate is then used to supply the BitRate value for the OpenHome Info service. 
sample_rate is used for the OpenHome Info SampleRate value.

But there are also static bitrate and sampleFrequency values which are part of the Content Directory descriptor for the file (which is also available to the Control Point, obviously).

So I would guess that the renderer with a changing display is showing the MPD kbit_rate value, and the other one is showing the sampling frequency  either from MPD (through OHInfo) or from the Content Directory record.

**Comment by rompolompo** [comment]
I tried with MPDroid and it also shows static info like: "FLAC 96kHz 24Bit" so I believe they are getting this info directly form MPD. It would be great to have this option as well (maybe a user setting?).

**Comment by medoc92** [comment]
Yes, but as far as I can see, this would be a Control Point option, not an upmpdcli one. 

What is the Control Point  showing the current and changing bit rate ? Actually I think that all of sample rate, bit depth, and current bit rate are interesting info. For example variable rate mp3s are often displayed with a 128 Kb/s static rate, but the actual rate is of course varying and quite different.

In any case, as far as I know, upmpdcli supplies all the available data, and it's up to the CP to know what it wants to show

**Comment by rompolompo** [comment]
I currently use BubbleUpnp. When used with my CH-Precision C1 Streamer, the info is shown as static but when using upmpdcli, hte info is show as mentioned. Both use Tidal and local MinimServer. Both times, I used Bubble on android. The only difference is the renderer.

**Comment by rompolompo** [comment]
I will get some screenshots and maybe logs when I get home tonight.

**Comment by medoc92** [comment]
I think that I have found the explanation: as far as I can see, bubble displays "FLAC 96kHz 24Bit" for UPnP AV renderers and "xxxxkbps | 192.0kHz" for OpenHome renderers because I can obtain either display by switching upmpdcli from one interface to the others.

So if this is important to you to the point of losing the OpenHome niceties, you can edit /etc/upmpdcli.conf and set upnpav = 1 and openhome = 0 to get the first kind of display.

**Comment by rompolompo** [comment]
Wow! That was fast. I will try it tonight.

**Comment by rompolompo** [comment]
What will I lose if I apply this change?

**Comment by medoc92** [comment]
OpenHome is more like MPD: the playlist belongs to the renderer and stays active even if the control point switches off. With bare UPnP AV, the music switches off at the next track if the CP is off. Also OpenHome is nicer with multiple control points.

More details here: http://www.lesbonscomptes.com/pages/homenet-audio.html
