### ISSUE TITLE
compiling on ArchLinux ARM doesn't work

### ISSUE THREAD

**Issue by marc-aurel** [medoc92/upmpdcli#22]
Hi,

I tried to compile upmpdcli on a Cubox i4-pro running ArchLinux
but it failed
Compiling libupnpp worked flawlessly.
Do I have to copy some parts of libupnpp to the upmpdcli directory?
I attached a textfile containing the error.

[make.txt](https://github.com/medoc92/upmpdcli/files/101826/make.txt)

**Comment by joerg-krause** [comment]
Did you installed libupnpp already?

**Comment by marc-aurel** [comment]
found the problem.
I didn't install the compiled new version of libupnpp because an older version from the archphile respository was still installed on the system.
replacing the old library with the new one fixed the problem.
