### ISSUE TITLE
Linn Kazoo does not recognize upmpdcli

### ISSUE THREAD

**Issue by nicolabotta** [medoc92/upmpdcli#23]
Hi,

upmpdcli has finally made it possible for me to use Minimserver without having to change my MPD-based system! **Thanks for developing upmpdcli!**

In http://www.lesbonscomptes.com/upmpdcli/control-points.html, you mention "_07-2015: later versions of Kazoo don't work with upmpdcli. I'm not sure that they work anymore with any non-Linn renderers actually_".

As it turns out, the current (4.8.927) Kazoo works fine with upmpdcli if one uses BubbleUPnP Server to "create an OpenHome renderer" on the top of upmpdcli. **This suggest that either upmpdcli does not fully support OpenHome or that Kazoo requires more than OpenHome** (and that BubbleUPnP Server provides such "more"). I have opened a thread on this issue in the Linn forum, please see

http://forums.linn.co.uk/bb/showthread.php?tid=32442&pid=384372#pid384372

I would be grateful if you could take a look at this issue. It would be great if Linn Kazoo would be able to discover upmpdcli without having to also run BubbleUPnP Server.

If it is possible to contribute to the development of upmpdcli with a donation, please let me know.

Best regards,
Nicola

**Comment by medoc92** [comment]
Hi, 

I understand that BubbleUPnP server fixes your issue, but I would not consider this as fixing the upmpdcli problem ! As you probably saw on the Linn forums, I asked for help so that upmpdcli can work with Kazoo natively, we'll see if anything comes out back.

**Comment by nicolabotta** [comment]
Jean-Francois Dockes <notifications@github.com> wrote:

> Hi,
> 
> I understand that BubbleUPnP server fixes your issue, but I would not consider this as fixing the upmpdcli problem ! As you
> probably saw on the Linn forums, I asked for help so that upmpdcli can work with Kazoo natively, we'll see if anything comes out
> back.

Jean-Francois,

I saw that, thanks! I certainly agree, the problem is not solved. It is
not even understood, in fact!

[Solved] was certainly the wrong expression, what I actually meant to
say is that we know a little bit better where the problem comes from: I
was not aware of the fact that if Kazoo does not manage to discover a
renderer, it never gets to recognize a server.

I have run BubbleUPnP Server only on my laptop for testing purposes. On
the music server, I would like to have a clean solution.

Kazoo is, at this stage, anyway almost unusable even if it manages to
connect to upmpdcli. After running for about 10 minutes on my wife's
iPad the device was frozen and we had to restart it.

Thanks for your support! I hope the Linn people will come back to you
with some usable information.

Best,
Nicola

**Comment by medoc92** [comment]
Status update: waiting for Linn feedback on the Linn forums:
http://forums.linn.co.uk/bb/showthread.php?tid=32442&pid=385029#pid385029

**Comment by espakman** [comment]
A few months ago there was an user on the Linn forum who made some wireshark traces and did found some differences in comparing traces from kazoo and Kinsky:
http://forums.linn.co.uk/bb/showthread.php?tid=30305

**Comment by medoc92** [comment]
This is fixed by a change to pupnp/libupnp:
https://sourceforge.net/p/pupnp/code/ci/91ef91e8531b86507f9a752316991221792db380/
And a change currently in the pipe for future Kazoo versions:
http://forums.linn.co.uk/bb/showthread.php?tid=32442&page=4

Each of the changes fixes the problem (you need only one).
