### ISSUE TITLE
upmpdcli, Kazoo and MinimServer: no artwork in "playing now" views 

### ISSUE THREAD

**Issue by nicolabotta** [medoc92/upmpdcli#29]
I am not sure, but this could be another idiosyncrasy between upmpdcli and Linn Kazoo. I have posted a full report on the Linn Forum: 

http://forums.linn.co.uk/bb/showthread.php?tid=32744 

It is a bit strange because the exactly the same problem occurs with Kinsky. On the other hand, upmpdcli has no problems displaying artwork in the "now playing" screens with the Lumin and Audionet control points.

By the way the Audionet control point works very well with upmpdcli! 

Best,
Nicola

**Comment by nicolabotta** [comment]
There is a twist: if I apply BubbleUPnP Server to wrap upmpdcli into an OpenHome renderer, artwork in the "now playing" screens of Kazoo is displayed flawlessly!

This suggests that there is at least one area in which Kazoo and Bubble UPnP use a different standard than upmpdcli.

Best regards,
Nicola

**Comment by medoc92** [comment]
I'll try to take a look at where kinsky and kazoo might get their artwork URIs from, but I can't do it in the following days, this will have to wait mid-march.

**Comment by nicolabotta** [comment]
Jean-Francois Dockes <notifications@github.com> wrote:

> I'll try to take a look at where kinsky and kazoo might get their
> artwork URIs from, but I can't do it in the following days, this will
> have to wait mid-march.

Thanks Jean-Francois! No hurry, the problem is there but there is no
urgency.

I am not sure it is an URI problem since wrapping upmpdcli with Bubble
UPnP Server solves the problem.

But, again, I understand very little of what is going on under the hood.

I just realized by chance that artwork was there when I streamed to a
Chromecast Audio and disappeared when I selected upmpdcli.

I thought that I would try to use Bubble UPnP Server to create an
OpenHome renderer with upmpdcli. And the artwork was there!

Perhaps it is just a matter of filling in some oh variables in
upmpdcli.conf.

I will play a little bit around during the weekend and report if I
manage to get some results.

Best,
Nicola

**Comment by medoc92** [comment]
I had a bit of time finally, and just pushed an update which should fix the album art issue. This was a pure upmpdcli problem this time as far as I can see.

**Comment by nicolabotta** [comment]
Jean-Francois Dockes <notifications@github.com> wrote:

> I had a bit of time finally, and just pushed an update which should
> fix the album art issue. This was a pure upmpdcli problem this time as
> far as I can see.

That sounds great Jean-Francois, but I do not see the update in

# upmpdcli
deb http://www.lesbonscomptes.com/upmpdcli/downloads/debian/ unstable main
deb-src http://www.lesbonscomptes.com/upmpdcli/downloads/debian/unstable main

Best,
Nicola

**Comment by medoc92** [comment]
nicolabotta writes:
 > Jean-Francois Dockes <notifications@github.com> wrote:
 > 
 > > I had a bit of time finally, and just pushed an update which should
 > > fix the album art issue. This was a pure upmpdcli problem this time as
 > > far as I can see.
 > 
 > That sounds great Jean-Francois, but I do not see the update in
 > 
 > # upmpdcli
 > deb http://www.lesbonscomptes.com/upmpdcli/downloads/debian/ unstable main
 > deb-src http://www.lesbonscomptes.com/upmpdcli/downloads/debian/unstable main
 > 
 > Best,
 > Nicola

It's only in git code for now. I'll build a release later.

**Comment by nicolabotta** [comment]
OK, thanks! Best, Nicola

**Comment by nicolabotta** [comment]
Hmm ... it appears that I cannot compile the git code on my Debian system:

```
...
checking for pthread_create in -lpthread... yes
checking for getsyshwaddr in -lupnpp... no
configure: error: libupnpp
```

Here is all upnp stuff on my system:

```
nicola@cirrus:~/src/upmpdcli-master$ apt list | grep upnp
gir1.2-gupnp-1.0/stable 0.20.12-1 amd64
gir1.2-gupnp-av-1.0/stable 0.12.6-1 amd64
gir1.2-gupnpdlna-2.0/stable 0.10.2-1 amd64
gir1.2-gupnpigd-1.0/stable 0.2.4-1 amd64
gupnp-dlna-tools/stable 0.10.2-1 amd64
gupnp-tools/stable 0.8.9-1 amd64
libgupnp-1.0-4/stable,now 0.20.12-1 amd64 [installed,automatic]
libgupnp-1.0-dbg/stable 0.20.12-1 amd64
libgupnp-1.0-dev/stable 0.20.12-1 amd64
libgupnp-av-1.0-2/stable,now 0.12.6-1 amd64 [installed,automatic]
libgupnp-av-1.0-dbg/stable 0.12.6-1 amd64
libgupnp-av-1.0-dev/stable 0.12.6-1 amd64
libgupnp-av-doc/stable 0.12.6-1 all
libgupnp-dlna-2.0-3/stable,now 0.10.2-1 amd64 [installed,automatic]
libgupnp-dlna-2.0-dbg/stable 0.10.2-1 amd64
libgupnp-dlna-2.0-dev/stable 0.10.2-1 amd64
libgupnp-dlna-doc/stable 0.10.2-1 all
libgupnp-doc/stable 0.20.12-1 all
libgupnp-igd-1.0-4/stable 0.2.4-1 amd64
libgupnp-igd-1.0-dbg/stable 0.2.4-1 amd64
libgupnp-igd-1.0-dev/stable 0.2.4-1 amd64
libgupnp-igd-1.0-doc/stable 0.2.4-1 all
libhupnp-dev/stable 1.0.0-1 amd64
libhupnp1/stable 1.0.0-1 amd64
libminiupnpc-dev/stable,stable 1.9.20140610-2+deb8u1 amd64
libminiupnpc10/stable,stable,now 1.9.20140610-2+deb8u1 amd64 [installed,automatic]
libmono-upnp-cil/stable 0.1.2-2 all
libmono-upnp-cil-dev/stable 0.1.2-2 all
libnet-upnp-perl/stable 1.4.2-1 all
libupnp-dev/unknown,now 1:1.6.19.jfd3-1 all [installed]
libupnp-java/stable 1.0.4+triplea-1 all
libupnp-java-doc/stable 1.0.4+triplea-1 all
libupnp6/unknown,now 1:1.6.19.jfd3-1 amd64 [installed,automatic]
libupnp6-dbg/unknown 1:1.6.19.jfd3-1 amd64
libupnp6-dev/unknown,now 1:1.6.19.jfd3-1 amd64 [installed,automatic]
libupnp6-doc/stable 1:1.6.19+git20141001-1 all
libupnpp-dev/unknown 0.9.0-1 amd64
libupnpp0/unknown 0.9.0-1 amd64
libupnpp1/unknown 0.10.0-1 amd64
libupnpp1-dev/unknown 0.10.0-1 amd64
libupnpp2/unknown,now 0.14.1-1 amd64 [installed,automatic]
libupnpp2-dev/unknown 0.14.1-1 amd64
libweupnp-java/stable 0.1.2-1 all
libweupnp-java-doc/stable 0.1.2-1 all
miniupnpc/stable,stable 1.9.20140610-2+deb8u1 amd64
miniupnpd/stable 1.8.20140523-4 amd64
mono-upnp-bin/stable 0.1.2-2 all
monodoc-mono-upnp-manual/stable 0.1.2-2 all
python-gupnp-igd/stable 0.2.4-1 amd64
python-miniupnpc/stable,stable 1.9.20140610-2+deb8u1 amd64
upnp-inspector/stable 0.2.2+dfsg-3 all
upnp-router-control/stable 0.2-1.2 amd64
nicola@cirrus:~/src/upmpdcli-master$
```

Best,
Nicola

**Comment by joerg-krause** [comment]
Your `libupnpp` is to old. You need to build version 0.14.1 for latest upmpdcli.

**Comment by nicolabotta** [comment]
I see, thanks! Best, Nicola

**Comment by nicolabotta** [comment]
Jean-Francois,

I have no urgency but, just for my planning, when do you plan to build a Debian release with the new code, roughly? 

Best, Nicola

**Comment by medoc92** [comment]
nicolabotta writes:
 >    Jean-Francois,
 > 
 >    I have no urgency but, just for my planning, when do you plan to build
 >    a Debian release with the new code, roughly?

Around the middle/end of next week probably.

**Comment by nicolabotta** [comment]
That's great Jean-Francois, thanks! Best, Nicola

**Comment by medoc92** [comment]
I've created the new Debian packages.

**Comment by nicolabotta** [comment]
Jean-Francois Dockes <notifications@github.com> wrote:

> I've created the new Debian packages.

Great, thanks a lot! Best, Nicola
