### ISSUE TITLE
Lumin for iOS not recognizing upmpdcli 1.1.2

### ISSUE THREAD

**Issue by exa062** [medoc92/upmpdcli#30]
After updating to Upmpdcli 1.1.2 Lumin is no longer able to see it. It is not listed by Lumin as available render.  Mconnect HD can see upmpdcli instances but it is unable to connect.  I've tested it with the Upmpdcli default settings and with all usable combinations of the flags that control Openhome and UPnP modes. 

PlugPlayer and Kazoo on iOS are working fine.

**Comment by medoc92** [comment]
What version were you running previously ?

**Comment by exa062** [comment]
Here are the old versions:
libupnpp1_0.10.0-1_amd64.deb
upmpdcli_0.11.2-1_amd64.deb

New versions:
libupnp6_1.6.19.jfd3-1_amd64.deb
libupnpp2_0.14.1-1_amd64.deb
upmpdcli_1.1.2-1_amd64.deb

**Comment by medoc92** [comment]
This is a bit strange because I have quite recent reports that Lumin works with upmpdcli. It may be because of a very recent change though. One thing which may trick you is that Lumin would now list upmpdcli under it's OpenHome name (Main Room by default), instead of its UPnP "friendly name" (upmpdcli by default, or whatever is set in the friendlyname parameter value). You can change the "Main Room" value by setting the ohproductroom parameter (see the commented sample file here:

**Comment by exa062** [comment]
I did try various options with the ohproductroom setting.  

ohproductroom = Main Room 
ohproductname = Upmpdcli-001

ohproductroom = Upmpdcli-001
ohproductname = Upmpdcli-001

Either way Lumin is not listing this device. Since there are no other renderers on the network, the box in the Lumin settings dropdown "Select Lumin" stays empty. PlugPlayer works in both configurations. 

All other things equal, Lumin can see the previous installation libupnpp1_0.10.0-1 / 
upmpdcli_0.11.2-1.

I also started upmpdcli in a terminal window.
sudo upmpdcli -l  4  -c /etc/upmpdcli.conf

Nothing unusual. No trace of communication with Lumin either.  I can see the trace messages from PlugPlayer.

**Comment by medoc92** [comment]
This is weird, I have a report of upmpdcli 1.1.0 and 1.1.2, with libupnpp 0.14.1 working with Lumin 6.0.1 on Iphone 6, and Ipad (Lumin version unknown). The fact that there are no traces of communication with Lumin would tend to indicate that things fail early in the discovery process.

Maybe try to purge Lumin and its data and retry ? I know that I've seen Kazoo issues purged this way.

**Comment by exa062** [comment]
No luck with purging Lumin. I tested on two iPads with the latest and much older iOS. The key here is that without any changes to the iPads my old configuration works and the new one is invisible to Lumin and causes error with MConnect HD. 

I will try a clean new Linux setup to see if anything on this side can make a difference.

**Comment by medoc92** [comment]
I have no idea about what can cause the difference between your situation and the other user's, still thinking about it. Unfortunately, I have no iOS device, so I can't test directly.

**Comment by exa062** [comment]
Thanks, I will try to investigate and provide more information.

**Comment by exa062** [comment]
I did a clean install of everything from scratch with the latest Upmpdcli 1.1.3 and now Lumin works fine.  Most likely the issue was with my setup, unfortunately I couldn't find the root cause.  Thank you very much for your time and effort.

**Comment by medoc92** [comment]
You are very much welcome, and I'm very glad that it works, because I was worried that I had broken Lumin by fixing Kazoo, and without any way to test !
