### ISSUE TITLE
Extract the audio data from mpd

### ISSUE THREAD

**Issue by maotouying** [medoc92/upmpdcli#32]
Hi:medoc92,
    I want to Extract the audio data from mpd before decoder,and send the audio data(as mp3,wav,flac) to others mpd(different devices),do you have a good method to do this? thanks a lot.

**Comment by medoc92** [comment]
No, sorry. no idea how to do this. This certainly need deep understanding of mpd internals, and programming. Then there would probably be major synchronization issues.
