### ISSUE TITLE
Upmpdcli /JRiver Volume Synchronization

### ISSUE THREAD

**Issue by exa062** [medoc92/upmpdcli#38]
I am trying to use upmpdcli as a UPnP renderer for JRiver Media Center.  It works very well, except a couple of issues related to volume commands.  

In the direction JRiver/JRemote to upmpdcli volume synchronization works pretty fast.  In the opposite direction,  from upmpdcli to JRiver volume synchronization can take up to 25 seconds. Volume synchronization works more or less reliably only during playback. The issues appear when playback is paused. 

See the attached file with information and comments from JRiver support.

[JRiver-upmpdcli.zip](https://github.com/medoc92/upmpdcli/files/246716/JRiver-upmpdcli.zip)

Do you see any possibility for improving the compatibility between upmpdcli and JRiver?

**Comment by medoc92** [comment]
Hi, and thanks for studying this in detail.

I am not sure about what happens with No 1/2, it would probably useful to also have the upmpdcli log while this happens.

I think that 3. should be ok, I don't think that upmpdcli generates short XML elements, except for LastChange data.

About 4, I just pushed an update to add  a channel attribute to the renderctl LastChange data elements. 

Can you build from git code, or would you like me to build a binary package for testing ? And if yes, for what platform/architecture ?

**Comment by exa062** [comment]
I am sorry, I couldn't make a working build.  Can you make a package for Ubuntu Intel x64.

**Comment by medoc92** [comment]
exa062 writes:
 >    I am sorry, I couldn't make a working build. Can you make a package for
 >    Ubuntu Intel x64.

Yes, I can do it, but not before the middle of next week.

**Comment by medoc92** [comment]
Forgot to ask: what ubuntu version ?

**Comment by exa062** [comment]
Can you just make updated version of your  .deb packages for amd64.  I will make a manual installation with 
libupnp6_1.6.19.jfd3-1_amd64.deb, 
libupnpp2_0.14.1-1_amd64.deb and 
upmpdcli_1.1.3-1_amd64.deb.

**Comment by medoc92** [comment]
I can easily do this, but these are Debian packages, and there is a good chance that they will not work on all Ubuntu versions. Anyway, we can try: I uploaded a package to http://lesbonscomptes.com/upmpdcli/files/

It's named upmpdcli-1.1.3, but it's actually built from current git code. If it works for you, I'll probably release an 1.1.4 soon. If there are packaging issues, I can easily build a proper Ubuntu package if you tell me your version.

**Comment by exa062** [comment]
Thanks, the current versions work just fine.

**Comment by medoc92** [comment]
Great ! Closing the issue then.
