### ISSUE TITLE
Ubuntu PPA: Undefined symbol

### ISSUE THREAD

**Issue by LaurensVanAcker** [medoc92/upmpdcli#40]
Hi

I had upmpcli running without problems on Ubuntu LTS 12.04.
I upgraded to LTS 14.04 and it gave some errors. I found in your bug tracker it was a bug from 6 months ago which was fixed.
So I did an apt-get –purge remove and installed from the PPA Ubuntu repository on your site.

The result is this error message. Any clue how to solve this?

laurens@Nova:/etc$ uname -r
4.4.0-28-generic
laurens@Nova:/etc$
laurens@Nova:/etc$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
laurens@Nova:/etc$
laurens@Nova:/etc$ sudo /usr/bin/upmpdcli -c /etc/upmpdcli.conf
/usr/bin/upmpdcli: symbol lookup error: /usr/bin/upmpdcli: undefined symbol: _ZN5UPnPP6Logger9getTheLogERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

Kind regards
Laurens Van Acker

**Comment by medoc92** [comment]
Fixed by updating libupnpp2. Probable dependancy checking issue in the PPA package (or ABI incompatibility bug)?
