### ISSUE TITLE
Symlinks in upmpdcli git code

### ISSUE THREAD

**Issue by espakman** [medoc92/upmpdcli#41]
Hi, 
I try to compile the latest upmpdcli git code but there are some symbolic links in git. For example: src/cdplugins/cmdtalk.cpp and .h and the files in pycommon/ are symlinks instead of real files.

Eric

**Comment by medoc92** [comment]
Sorry about this, I just fixed it. 
I am implementing support for playing music from Tidal, and the code may be less stable than desirable, I'm mostly using github as a backup server... 

If you have a tidal account, and feel adventurous, I'd be interested by your feedback. You need to add something like the following to /etc/upmpdcli.conf:

    tidaluser = mytidallogin
    tidalpass = mytidalpassword
    tidalquality = high

I have only tested quality high and low for now, not lossless, which probably does not work for the moment.

After restarting upmpdcli, you should see a new media server on the network (name based on the one from the upmpdcli renderer). You should be able to use it and add tracks to the playlist.

Search is not implemented yet and 'favourite artists' does not work for some reason.
