### ISSUE TITLE
Do not start with symbol lookup error message

### ISSUE THREAD

**Issue by parkmino** [medoc92/upmpdcli#42]
Hi,
I updated Ubuntu 16.04 ppa and upmpdcli & upplay does not start with symbol lookup error message as follows.
"upmpdcli: symbol lookup error: upmpdcli: undefined symbol: _ZN10UPnPClient13UPnPDirObject7nullstrB5cxx11E"
"upplay: symbol lookup error: upplay: undefined symbol: _ZN10UPnPClient13UPnPDirObject7nullstrB5cxx11E"

**Comment by joerg-krause** [comment]
Did you updated libupnpp as well?

**Comment by parkmino** [comment]
libupnpp3 0.15.0-1 version installed, the same as the repository.

**Comment by medoc92** [comment]
It seems that a part of the update went wrong, I just re-checked the packages from the PPA, and they seem to run well. 

Is your system using a 32 or 64 bits installation (uname  -a) ?

I'd first try to reinstall, making sure I get fresh packages:

    sudo apt-get clean
    sudo apt-get install --reinstall upmpdcli upplay libupnpp3 

If this does not change anything, can you please try to run:

    ldd /usr/bin/upmpdcli

and post the output.

**Comment by parkmino** [comment]
Thanks for your advice and resolved!

libupnppp3 couldn't be reinstalled on my 64bit Ubuntu 16.04.
Now that all the packages has been deleted and reinstalled through synaptic, it works fine.
I tried manual installation yesterday and it seems to have caused this issue.
No problem on PPA as you pointed out.
