### ISSUE TITLE
upmpdcli 1.2.2  DSD files can no longer be added to a playlist. 

### ISSUE THREAD

**Issue by exa062** [medoc92/upmpdcli#43]
Hello,

After updating to upmpdcli 1.2.2  DSD files can no longer be added to a playlist.  I tested with Kazoo, Lumin, PlugPlayer and other control points.  If DSD files are added to the MPD playlist with other means, they play fine. 

Here is a fragment of the upmpd log file:

:4:libupnpp/device/device.cxx:318::UPNP_CONTROL_ACTION_REQUEST: IdArray. Params: <?xml version="1.0"?>
<u:IdArray xmlns:u="urn:av-openhome-org:service:Playlist:1"></u:IdArray>

:4:src/ohplaylist.cxx:726::OHPlaylist::idArray
:4:src/ohplaylist.cxx:744::OHPlaylist::idArray (internal)
:4:src/ohplaylist.cxx:747::OHPlaylist::idArray: qvers 12
:4:libupnpp/device/device.cxx:318::UPNP_CONTROL_ACTION_REQUEST: Insert. Params: <?xml version="1.0"?>
<u:Insert xmlns:u="urn:av-openhome-org:service:Playlist:1">
<AfterId>6</AfterId>
<Uri>http://192.168.4.104:8200/MediaItems/453.dsf</Uri>
<Metadata>&lt;DIDL-Lite xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot;&gt;
  &lt;item&gt;
    &lt;dc:title xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot;&gt;DSD256 2006 nagano ohba&lt;/dc:title&gt;
    &lt;upnp:class xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot;&gt;object.item.audioItem.musicTrack&lt;/upnp:class&gt;
    &lt;res sampleFrequency=&quot;11289600&quot; bitrate=&quot;22579200&quot;&gt;http://192.168.4.104:8200/MediaItems/453.dsf&lt;/res&gt;
  &lt;/item&gt;
&lt;/DIDL-Lite&gt;</Metadata>
</u:Insert>

:4:src/ohplaylist.cxx:615::OHPlaylist::insert
:4:src/ohplaylist.cxx:638::OHPlaylist::insert: afterid 6 Uri http://192.168.4.104:8200/MediaItems/453.dsf Metadata <DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/">
  <item>
    <dc:title xmlns:dc="http://purl.org/dc/elements/1.1/">DSD256 2006 nagano ohba</dc:title>
    <upnp:class xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">object.item.audioItem.musicTrack</upnp:class>
    <res sampleFrequency="11289600" bitrate="22579200">http://192.168.4.104:8200/MediaItems/453.dsf</res>
  </item>
</DIDL-Lite>
:2:src/upmpd.cxx:147::checkContentFormat: resource has no protocolinfo
:2:src/ohplaylist.cxx:663::OHPlaylist::insertUri: unsupported format: uri http://192.168.4.104:8200/MediaItems/453.dsf metadata <DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/">
  <item>
    <dc:title xmlns:dc="http://purl.org/dc/elements/1.1/">DSD256 2006 nagano ohba</dc:title>
    <upnp:class xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/">object.item.audioItem.musicTrack</upnp:class>
    <res sampleFrequency="11289600" bitrate="22579200">http://192.168.4.104:8200/MediaItems/453.dsf</res>
  </item>
</DIDL-Lite>:2:libupnpp/device/device.cxx:354::UpnpDevice: Action failed: Insert code -911
:4:libupnpp/device/device.cxx:318::UPNP_CONTROL_ACTION_REQUEST: SetSourceIndex. Params: <?xml version="1.0"?>
<u:SetSourceIndex xmlns:u="urn:av-openhome-org:service:Product:1">
<Value>0</Value>
</u:SetSourceIndex>

:4:src/ohproduct.cxx:311::OHProduct::setSourceIndex
:4:src/ohproduct.cxx:244::OHProduct::iSetSourceIndex: current 0 new 0

Can you help?

Kind regards,
George

**Comment by medoc92** [comment]
I think that adding 'checkcontentformat = 0' to the configuration file (/etc/upmpdcli.conf) should fix this.

But the basic problem here is that the Media Server should set a protocolinfo attribute inside the resource descriptor and it does not. Example of protocolinfo attribute:

    protocolInfo="http-get:*:audio/mpeg:*

In particular this defines the MIME type of the resource, and lets the control point check that it is compatible with the Renderer, or chose the right resource if several are available with different formats.

What Media Server are you using ?

**Comment by exa062** [comment]
Adding 'checkcontentformat = 0' did the trick  - thank you! 
I was using MinimServer 0.8.2 update 42.
