### ISSUE TITLE
Error while attempting to use Tidal

### ISSUE THREAD

**Issue by exa062** [medoc92/upmpdcli#50]
I am trying to configure Upmpdcli for use with Tidal. I have a working Tidal account configured with tidaluser / tidalpass.  I can see the new UPnP server exposing a Tidal node when browsed from a UPnP control point.  Accessing the Tidal node  causes the UPnP control point to display an error: "Service login or communication failure"
I am using Lubuntu 14.4 and I think I've done everything required for the Upmpdcli 1.2.2 installation and setup.  Below is a fragment of the Upmpdcli output.  Can you help?  

Thanks,
George

CMDTALK: tidal-app.py: Tidal running
CMDTALK: tidal-app.py: pCmdTalkProcessor.process: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: browse: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: processmessage: processor raised: [500 Server Error: Internal Server Error]
:2:src/mediaserver/cdplugins/plgwithslave.cxx:374::PlgWithSlave::browse: slave failure
CMDTALK: tidal-app.py: pCmdTalkProcessor.process: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: browse: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: processmessage: processor raised: [500 Server Error: Internal Server Error]
:2:src/mediaserver/cdplugins/plgwithslave.cxx:374::PlgWithSlave::browse: slave failure
CMDTALK: tidal-app.py: pCmdTalkProcessor.process: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: browse: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: processmessage: processor raised: [500 Server Error: Internal Server Error]
:2:src/mediaserver/cdplugins/plgwithslave.cxx:374::PlgWithSlave::browse: slave failure
CMDTALK: tidal-app.py: pCmdTalkProcessor.process: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: browse: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: processmessage: processor raised: [500 Server Error: Internal Server Error]
:2:src/mediaserver/cdplugins/plgwithslave.cxx:374::PlgWithSlave::browse: slave failure
CMDTALK: tidal-app.py: pCmdTalkProcessor.process: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: browse: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: processmessage: processor raised: [500 Server Error: Internal Server Error]
:2:src/mediaserver/cdplugins/plgwithslave.cxx:374::PlgWithSlave::browse: slave failure
CMDTALK: tidal-app.py: pCmdTalkProcessor.process: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: browse: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: processmessage: processor raised: [500 Server Error: Internal Server Error]
:2:src/mediaserver/cdplugins/plgwithslave.cxx:374::PlgWithSlave::browse: slave failure
CMDTALK: tidal-app.py: pCmdTalkProcessor.process: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: browse: [{u'cmdtalk:proc': 'browse', u'flag': 'children', u'objid': '0$tidal$'}]
CMDTALK: tidal-app.py: processmessage: processor raised: [500 Server Error: Internal Server Error]
:2:src/mediaserver/cdplugins/plgwithslave.cxx:374::PlgWithSlave::browse: slave failure

**Comment by medoc92** [comment]
exa062 writes:
 >    I am trying to configure Upmpdcli for use with Tidal. I have a working
 >    Tidal account configured with tidaluser / tidalpass. I can see the new
 >    UPnP server exposing a Tidal node when browsed from a UPnP control
 >    point. Accessing the Tidal node causes the UPnP control point to
 >    display an error: "Service login or communication failure"
 >    I am using Lubuntu 14.4 and I think I've done everything required for
 >    the Upmpdcli 1.2.2 installation and setup. Below is a fragment of the
 >    Upmpdcli output. Can you help?
 > 
 >    Thanks,
 >    George

Hi,

The log shows "internal server errors". These are from Tidal, and I have no
idea what can cause them. This normally signals an issue on the server
side. Did you try to change the quality parameter to see if it changed
anything ? It should not actually, because the error appears to occur while
logging in (this is the only reason the module has to talk to tidal at this
stage).

The upmpdcli plugin code is quite closely based on the Kodi add-on. It
would be interesting to install Kodi and try the add-on, to see if it works
or if it is getting the same error.

Cheers,

jf

**Comment by medoc92** [comment]
Actually I'm getting the same errors here. I should have checked before responding. So I can do the Kodi test myself. Either Tidal is having problems or they decided that they don't want to talk to us any more...

**Comment by medoc92** [comment]
Update again: kodi is listing tracks, but playing does not work. I can get upmpdcli to the same point, but I'm getting garbage when I try to access the music (so same as Kodi).

My best guess at this point is that either Tidal is experiencing internal issues, or they did something voluntarily or not which disabled the Api used by Kodi (and upmpdcli). Let's wait tomorrow...

**Comment by exa062** [comment]
Thanks, lets wait and see if the Tidal service becomes accessible.

**Comment by medoc92** [comment]
It certainly appears that Tidal has stopped working. I'll be looking for a solution, but don't hold your breath :( Meanwhile, Qobuz works just fine...

**Comment by exa062** [comment]
Thank you.  Please let me know if you manage to revive the Tidal functionality.

**Comment by medoc92** [comment]
Should be fixed by the recent upmpdcli-tidal 1.2.5
