### ISSUE TITLE
upmpdcli 1.2.2 does not play mp4/audio

### ISSUE THREAD

**Issue by parkmino** [medoc92/upmpdcli#53]
The latest upmpdcli does not play mp4/audio out of mp4/video even though mpd can do that through ffmpeg decoder.
I had enjoyed youtube audio with bubbleupnp but not any more.
'checkcontentformat = 0' resolves this issue, however I want not to block the file format that mpd and ffmpeg supports.
Please refer to the following error message.

:3:libupnpp/control/cdircontent.cxx:108::checkobjok: found object of unknown class: [object.item.videoItem]
:2:src/upmpd.cxx:152::checkContentFormat: **unsupported:: video/mp4**
:2:src/ohplaylist.cxx:663::OHPlaylist::insertUri: unsupported format: uri
...

**Comment by medoc92** [comment]
I just committed a change to fix this. You can just add the following line to /usr/share/upmpdcli/protocolinfo.txt. (Then restart upmpdcli)

    http-get:*:video/mp4:*

**Comment by parkmino** [comment]
Thanks for your support.

However ',' seems to missing at the end of previous line

**Comment by medoc92** [comment]
Min-ho Park writes:
 > Thanks for your support.
 > 
 > However ',' seems to missing at the end of previous line

Sorry, and thanks, this should be fixed now.
