### ISSUE TITLE
protocolInfo is buggy

### ISSUE THREAD

**Issue by bubbleguuum** [medoc92/upmpdcli#56]
As of v1.2.6. Both returned by ConnectionManager::GetProtocolInfo and
Playlist::ProtocolInfo: 

``
,,,http-get:*:audio/dsf:*,http-get:*:audio/x-dsf:*,http-get:*:audio/dsd:*,http-get:*:audio/x-dsd:*,http-get:*:audio/dff:*,http-get:*:audio/x-dff:*,http-get:*:audio/wav:*,http-get:*:audio/wave:*,http-get:*:audio/x-wav:*,http-get:*:audio/x-aiff:*,http-get:*:audio/mpeg:*,http-get:*:audio/x-mpeg:*,http-get:*:audio/mp1:*,http-get:*:audio/aac:*,http-get:*:application/flac:*,http-get:*:audio/flac:*,http-get:*:audio/x-flac:*,http-get:*:audio/m4a:*,http-get:*:audio/mp4:*,http-get:*:audio/x-m4a:*,http-get:*:audio/vorbis:*,http-get:*:audio/x-vorbis:*,http-get:*:audio/x-vorbis+ogg:*,http-get:*:audio/ogg:*,http-get:*:audio/x-ogg:*,http-get:*:audio/x-scpls:*,http-get:*:video/mp4:*,,,
``

Notice the extra commas at the beginning and the end. It makes at least BubbleUPnP fail to parse it.

**Comment by medoc92** [comment]
Thanks ! So little code, so many bugs...
It should be fixed in git now, I am rebuilding the packages, they will be out in the next hour.

**Comment by bubbleguuum** [comment]
Thanks! Also made a trivial fix in BubbleUPnP so it parses quoted protocolInfo.
