### ISSUE TITLE
:2:libupnpp/upnpplib.cxx:149::UpnpInit :-205: UPNP_E_OUTOF_SOCKET

### ISSUE THREAD

**Issue by Acer54** [medoc92/upmpdcli#58]
Hi,
upmpdcli was exactelly what I was looking for. Initially I have tried it on my Ubuntu 16.04, installed via the PPA "ppa:jean-francois-dockes/upnpp1" . After a first successful trial, I tried to install upmpdcli to my Raspberry Pi (Rasbian Jessy), (was using the way via creating a new sources.list with the unstable repo) but after successful installation on the pi, I get ":2:libupnpp/upnpplib.cxx:149::UpnpInit :-205: UPNP_E_OUTOF_SOCKET" after calling upmpdcli from my terminal.
Any idea what is wrong here ?

**Comment by Acer54** [comment]
Additional Info: Just tried it with another Pi (running Wheezy instead of Jessie) -> Installed and running with no Problem with the same approach like above.

**Comment by medoc92** [comment]
libupnp returns this error when a socket() call fails. If you try "man socket", you will see that there are a number of possible conditions to cause this: such as kernel out of open file entries, protocol not supported etc. My best guess is that this is a kernel configuration issue. Maybe no support for multicast ? Except if you have a lot of stuff running on this rpi, or you love dealing with kernel parameters, I'd just reinstall it from scratch. The way to debug this would be to enable or add traces in libupnp to check which calls fails and with what errno, but, given that I've never seen this happen before, I'm not sure it's worth the trouble.

**Comment by Acer54** [comment]
Hey Medoc, thanks for your reponse. Good to here that I am the only one with this error-message... Maybe I´ve messed up things during previouse tries.

**Comment by empierre** [comment]
Same issue for me

**Comment by medoc92** [comment]
Please describe your configuration: machine, system, exactly what package you installed and from where.

**Comment by empierre** [comment]
Volumio 1.5 image
Linux volumio 3.18.5-v7+ #748 SMP PREEMPT Wed Feb 4 21:33:52 GMT 2015 armv7l GNU/Linux

have this on command line, although the one launched from volumio seems to start

**Comment by empierre** [comment]
so in fact no logging, so launching it as volumio I have this in log:

 /usr/bin/upmpdcli -f volumio -l 2 
libupnpp/upnpplib.cxx:92::UpnpInit :-205: UPNP_E_OUTOF_SOCKET

**Comment by medoc92** [comment]
And when launched from volumio it works ??

**Comment by empierre** [comment]
don't know th at is why I was looking at it... bubbleupnp does not see it

wlan0     Link encap:Ethernet  HWaddr 7c:dd:90:7e:ba:ee
          inet addr:192.168.0.19  Bcast:192.168.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5045 errors:0 dropped:1471 overruns:0 frame:0
          TX packets:1658 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:932811 (910.9 KiB)  TX bytes:1095858 (1.0 MiB)

**Comment by medoc92** [comment]
A few more questions:
 - What board are you using (rpi 1/2/3...) ?
 - Any reason why you are using an old volumio release ? (not that I think it's related, just curious).
 - Have you got a possibility to try this with a wired connection ?

**Comment by empierre** [comment]
Hi,

  - PI2
  - volumio2 samba/nfs support was not working (at the last time I tried it) so went back on a working version
  - no wired sadly...

**Comment by medoc92** [comment]
Ok, I'll download volumio 1.5 and give it a try...

**Comment by empierre** [comment]
trying with your repo on my jessie, same issue

**Comment by medoc92** [comment]
I have it running here on wheezy, the ifconfig output on wlan0 is very similar. 

What does the full ifconfig output look like (lo and eth0) ? 

I wonder if it might be trying to use the wrong interface (really poking in the dark here). You could try setting:

    upnpiface = wlan0

in /etc/upmpdcli.conf

**Comment by empierre** [comment]
root@volumio:~# ifconfig
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:1595 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1595 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:190083 (185.6 KiB)  TX bytes:190083 (185.6 KiB)

wlan0     Link encap:Ethernet  HWaddr 7c:dd:90:7e:ba:ee
          inet addr:192.168.0.19  Bcast:192.168.0.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:63154 errors:0 dropped:2815 overruns:0 frame:0
          TX packets:13243 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:77239063 (73.6 MiB)  TX bytes:2670105 (2.5 MiB)

I did already pass -i wlan0 on command line with same result

**Comment by empierre** [comment]
hmmm... will try to bypass this running it from an odroid XU3 linked to the
mpd from volumio.

launched it fine on this platform !

**Comment by medoc92** [comment]
Well yes, upmpdcli does work in general :) There must be a very specific problem here because I only heard of it twice, and there are quite probably many thousands of working installations...

There is something weird in the ifconfig output though: it does not list eth0. Even if this is not connected, it should be listed. On my wireless pi, I have the following as part of the dmesg output:

````
eth0      Link encap:Ethernet  HWaddr b8:27:eb:94:14:a2  
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
````

I don't know that this is significant, but we're looking for something weird anyway... a pi2 should have eth0

Also: anything showing in dmesg when you get the out of sockets error ?

**Comment by empierre** [comment]
Hello,

  I did put down the eth0 witout any change, this is the reason you don't
see it.

  Nothing in the dmesg, I did a lot of reboot but never any message.

**Comment by medoc92** [comment]
Up or down, it should show in 'ifconfig' output ?

Anything special about your 'jessie' system configuration ? If it's vanilla, I think that we are more or less down to hardware... No idea how a wireless adapter could cause this though. What are you using ?

**Comment by empierre** [comment]
I did put eth0 down, no behavior change.

I did not update to newer kernel for I (used to have) IQ-DAC+ thouth now I
have a minidsp 2x4 HD on it.

[    3.733549] usb 1-1.4: Product: 802.11 n WLAN
[    3.739805] usb 1-1.4: Manufacturer: Ralink
[    3.745823] usb 1-1.4: SerialNumber: 1.0

**Comment by medoc92** [comment]
What I find strange is that ifconfig does not list eth0 at all. Can you send the full output of 'ifconfig -a' ?

I think that I'm going to buy a ralink adapter and give it a try. What model/chipset are you using ?

**Comment by medoc92** [comment]
No feedback on this issue and issue #108 seems to confirm that this is a configuration issue.
