### ISSUE TITLE
Won't start on RasPi 3

### ISSUE THREAD

**Issue by maulwuff** [medoc92/upmpdcli#61]
I get this when starting from shell:

```
# /usr/bin/upmpdcli 
pure virtual method called
terminate called without an active exception
Abgebrochen
```

```
# /usr/bin/upmpdcli -c /etc/upmpdcli.conf
pure virtual method called
terminate called without an active exception
Abgebrochen
```

This is with v1.2.9
Earlier versions of upmpdcli did work.

```
cat /proc/version 
Linux version 4.4.27-2-osmc (root@vero2a) (gcc version 4.9.2 (Debian 4.9.2-10) )
```

 The log shows:
```
cat /var/log/upmpdcli.log 
:4:src/mpdcli.cxx:128::MPDCLi::openconn: mpd protocol version: 0.19.0
:4:libupnpp/upnpplib.cxx:155::LibUPnP: Using IP 192.168.0.117 port 49152
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:AVTransport]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:RenderingControl]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:ConnectionManager]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Info]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Time]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Volume]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Playlist]
```

Any clue what is happening here? I also tried downgrading to 1.2.5 but this version doesn't seem to be in the repo anymore?
It works fine on my Linux Mint 17.3

**Comment by medoc92** [comment]
It seems that the raspbian package do not work on Debian any more (guessing that you are not running Raspbian). Look for 'ARM Debian note' on this page: http://lesbonscomptes.com/upmpdcli/downloads.html for instructions on rebuilding the package on your system.

http://lesbonscomptes.com/upmpdcli/upmpdcli-debian-build.txt

**Comment by maulwuff** [comment]
Ok I'll give it a try. 

> OSMC is based on Debian Linux and Kodi Media Center.

It says

**Comment by maulwuff** [comment]
I started from a completely clean non-dev OSMC install. 
The package `build-essential` is missing from the apt-get part, which makes `debuild -us -uc` fail. after installing this, it succeeded running debuild.
further down it says `cd upmpdcli-1.2.4/` which is 1.2.9 atm.

After all steps, I had my upmpdcli back online ;-)

**Comment by medoc92** [comment]
Thanks for the feedback ! I corrected the build document.
