### ISSUE TITLE
Error connecting to Qobuz

### ISSUE THREAD

**Issue by dahumph** [medoc92/upmpdcli#62]
running latest upmpdcli and upmpdcli-qobuz on a raspberry pi (1.2.9-1) 
- upmpdcli.conf set up with proper login details
- control point shows the new generated mediaserver, but error message "Service login or   communication failure" is displayed when trying to open qobuz.

Any advice what might be the problem? 

here is part of the log

:4:src/mediaserver/contentdirectory.cxx:288::ContentDirectory::actBrowse:  ObjectID 0$qobuz$ BrowseFlag BrowseDirectChildren Filter  StartingIndex 0 RequestedCount 1 Sort$
:4:src/mediaserver/cdplugins/cmdtalk-fixed.cpp:62::CmdTalk::startCmd
:4:src/execmd-fixed.cpp:454::ExecCmd::startExec: (1|1) /usr/share/upmpdcli/cdplugins/qobuz/qobuz-app.py
:4:src/execmd-fixed.cpp:891::ExecCmd::getline: timeout
:4:src/execmd-fixed.cpp:901::ExecCmd::getline: got 0
:2:src/mediaserver/cdplugins/cmdtalk-fixed.cpp:101::CmdTalk: getline error
:4:src/execmd-fixed.cpp:274::ExecCmd: killpg(3471, SIGTERM)
:2:src/mediaserver/cdplugins/plgwithslave.cxx:375::PlgWithSlave::browse: slave failure
:4:libupnpp/device/device.cxx:318::UPNP_CONTROL_ACTION_REQUEST: Browse. Params: <?xml version="1.0"?>
<u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
<ObjectID>0$qobuz$</ObjectID>
<BrowseFlag>BrowseDirectChildren</BrowseFlag>
<Filter>*</Filter>
<StartingIndex>0</StartingIndex>
<RequestedCount>1</RequestedCount>
<SortCriteria></SortCriteria>
</u:Browse>

**Comment by medoc92** [comment]
Could you please stop the regular upmpdcli (sudo systemctl stop upmpdcli, or the equivalent for your system), and start it on the command line like:

    sudo /usr/bin/upmpdcli -c /etc/upmpdcli.conf

And then retry the qobuz connection. This will allow us to see whatever the python module is possibly printing to stderr.

If you are running under systemd, you can also let it run and use 'journaltcl -u upmpdcli -f' instead of the above to see the messages.

**Comment by dahumph** [comment]
Hello medoc92,
and thanks for having a look at that issue.

this is the result of sudo /usr/bin/upmpdcli -c /etc/upmpdcli.conf. 

its constandly repeating....

ImportError: No module named requests
:2:src/mediaserver/cdplugins/cmdtalk-fixed.cpp:101::CmdTalk: getline error
:2:src/mediaserver/cdplugins/plgwithslave.cxx:375::PlgWithSlave::browse: slave failure
Traceback (most recent call last):
  File "/usr/share/upmpdcli/cdplugins/qobuz/qobuz-app.py", line 37, in <module>
    from session import Session
  File "/usr/share/upmpdcli/cdplugins/qobuz/session.py", line 11, in <module>
    from qobuz.api import raw
  File "/usr/share/upmpdcli/cdplugins/qobuz/api/raw.py", line 20, in <module>
    import requests
ImportError: No module named requests
:2:src/mediaserver/cdplugins/cmdtalk-fixed.cpp:101::CmdTalk: getline error
:2:src/mediaserver/cdplugins/plgwithslave.cxx:375::PlgWithSlave::browse: slave failure
Traceback (most recent call last):
  File "/usr/share/upmpdcli/cdplugins/qobuz/qobuz-app.py", line 37, in <module>
    from session import Session
  File "/usr/share/upmpdcli/cdplugins/qobuz/session.py", line 11, in <module>
    from qobuz.api import raw
  File "/usr/share/upmpdcli/cdplugins/qobuz/api/raw.py", line 20, in <module>
    import requests
ImportError: No module named requests

**Comment by medoc92** [comment]
You need to install python-requests. Sorry, this should have been in the deps, and it will be in a future version.

**Comment by dahumph** [comment]
that solved it! thanks!
