### ISSUE TITLE
Qobuz search not working

### ISSUE THREAD

**Issue by dahumph** [medoc92/upmpdcli#63]
Hello Medoc92,
it's me again... ;)
after testing streaming with the qobuz plugin, I can say streaming works like a charms, its fast and premium audio quality, running upmpdcli on Volumio 2.
As I saw on your website, you are waiting for indications of interest and comments to try and improve the features. well, here we go!

the biggest issue is the search feature, what makes the plugin hardly usable for me right now. I'm not sure if its only me having this problem, but I dont think so.

I searched for the term "Metallica" and the outcome is a list of 14 tracks in total, some related
to metallica, some are justin bieber...

as I could see in the py script, I would expect search topics like Tracks, Albums, Artists, Playlists...

but it only shows Tracks.

attached is the output of sudo /usr/bin/upmpdcli -c /etc/upmpdcli.conf
[output.txt](https://github.com/medoc92/upmpdcli/files/600533/output.txt)

thanks again!

**Comment by medoc92** [comment]
Yes, search is not working right. I'll give it another try. What makes things complicated is that the different control points issue different kinds of UPnP searches, which I have to parse (sort of), and then map to Qobuz searches, and the fit is not easy. What CP are you using ?

**Comment by dahumph** [comment]
I used Linn Kazoo on iOS

**Comment by medoc92** [comment]
I have uploaded a new version which should vastly improve the search (not perfect yet, but making progress hopefully).

**Comment by serverbaboon** [comment]
This is a lot better, possible to find things now. Also the Bubble CP function to find albums by the currently playing artist now works as well.

Noted that you are now passing back the album in the meta data which is is good for the control point.

Adding something from your album favourites in Qobuz also is now added as an album and not several individual tracks which it was before.

**Comment by dahumph** [comment]
Hi, 
sorry, for me no improvment with the new version. When I start entering a search string, the "Service login or communication failure" error is back. When I do not search but just click through the menue like Genre/Pop and Rock/New Releases/ all works well, even streaming no problem. 

here is what happens:


:2:src/mediaserver/contentdirectory.cxx:408::ContentDirectory::actSearch: Can't search in root. Substituting last browsed container
CMDTALK: qobuz-app.py: pCmdTalkProcessor.process: [{u'cmdtalk:proc': 'search', u'field': 'track', u'objid': '0$qobuz$', u'value': 'metallica'}]
CMDTALK: qobuz-app.py: search: [{u'cmdtalk:proc': 'search', u'field': 'track', u'objid': '0$qobuz$', u'value': 'metallica'}]
CMDTALK: qobuz-app.py: processmessage: processor raised: [unsupported operand type(s) for +: 'NoneType' and 'str']
:2:src/mediaserver/cdplugins/plgwithslave.cxx:556::PlgWithSlave::search: slave failure

**Comment by dahumph** [comment]
Same here, big improvement! Thanks!
