### ISSUE TITLE
compiling upmpdcli fails

### ISSUE THREAD

**Issue by maulwuff** [medoc92/upmpdcli#66]
Can you help me with this:
```
configure:2851: checking for C++ compiler version
configure:2860: g++-4.7 --version >&5
/usr/bin/g++-4.7: not found (maybe g++-4.7 is not installed?)
configure:2871: $? = 127
configure:2860: g++-4.7 -v >&5
/usr/bin/g++-4.7: not found (maybe g++-4.7 is not installed?)
configure:2871: $? = 127
configure:2860: g++-4.7 -V >&5
/usr/bin/g++-4.7: not found (maybe g++-4.7 is not installed?)
configure:2871: $? = 127
configure:2860: g++-4.7 -qversion >&5
/usr/bin/g++-4.7: not found (maybe g++-4.7 is not installed?)
configure:2871: $? = 127
configure:2891: checking whether the C++ compiler works
configure:2913: g++-4.7 -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wl,-z,relro conftest.cpp  >&5
/usr/bin/g++-4.7: not found (maybe g++-4.7 is not installed?)
configure:2917: $? = 127
configure:2955: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "upmpdcli"
| #define PACKAGE_TARNAME "upmpdcli"
| #define PACKAGE_VERSION "1.2.10"
| #define PACKAGE_STRING "upmpdcli 1.2.10"
```

For g++ I have
```
g++           g++-4.2       g++-4.3       g++-4.4       g++-4.5       g++-4.6       g++-4.7       g++-4.8       g++-4.9       g++-4.9.real  
```

The script seems to loop using the same value for g++ over and over - that's what I read from this section of the file.

**Comment by medoc92** [comment]
Just so that I know exactly what you are doing: are you building from the git source, a tar distribution, or a source package ?

Also: on what platform ? (I'm guessing Debian?)

What happens if you just type g++-4.7 on the command line ?

**Comment by maulwuff** [comment]
I follow the instructions from https://www.lesbonscomptes.com/upmpdcli/upmpdcli-debian-build.txt 

on a raspberry pi 3 with Debian ARM. 
g++-4.7 says not  found (dunno the exact wording, it is similar to the output posted above) , the only one which seems to work is g++-4.9

**Comment by medoc92** [comment]
Ok, I see what's happening, my bad. I am going to fix the source package (it has an option which only makes sense on wheezy). Meanwhile, you should be able to fix things locally.
After changing your current directory to upmpdcli-2.10, edit debian/rules, comment out the `export CXX=g++-4.7` line, and then follow the rest of the procedure.

**Comment by maulwuff** [comment]
thanks, this worked :)
