### ISSUE TITLE
improving qobuz search further...

### ISSUE THREAD

**Issue by dahumph** [medoc92/upmpdcli#68]
Hi, the last weeks I was using upmpdcli often to stream music from NAS as well as qobuz, works very good so far, actually it has become my main mpd and qobuz client. great job! If you would like to improve further here's one more thing...

Qobuz natively features the discover section, which hast subsections like playlists, most streamed, most downloaded, press awards etc...

when I use the discover feature with upmpdcli, this works for playlists only, missing the highly appreciated streaming charts and the other subsections. I can actually find them under the "Genre/pop_Rock section, but here it is only by this specific genre, not the "at all" streaming charts.

greez 
humph

**Comment by medoc92** [comment]
Hi,
Not currently at home, but I'm not forgetting you: I'll take a look as soon as I can.

**Comment by medoc92** [comment]
Had a quick look and it seems that you can improve things a bit by using the git code for qobuz: replace  /usr/share/upmpdcli/cplugins/qobuz with src/mediaserver/cdplugins/qobuz/ from git

**Comment by dahumph** [comment]
thanks medoc, this improved the search by means of found items are not restricted to 40 in total any more. But sure you already know that it does not bring the categories back;)

greez humph

**Comment by medoc92** [comment]
The Qobuz interface should be hopefully improved in the just released upmpdcli 1.2.11 (contents should be closer to what the Qobuz web player shows). Please give it a try when you have a moment.

**Comment by dahumph** [comment]
Hi and thanks for this update! Unfortunatelly, it makes things worse with my control point (Kazoo on iOS). It's only showing the first 2 topics under each category, e.g. under qobuz/discover genres/ it shows only all genres and pop/rock. same issue under every topic only 2 subtopics are displayed. with upplay it works perfect, shows all categories and the most streamed etc, so I guess its only a small issue with certain control points. If you can establish compatibility here, the qobuz side of upmpdcli would be perfect.

greez and happy 2017

**Comment by medoc92** [comment]
The 2 last changes in the git repo should fix the problems seen by Kazoo.

Can you test this easily or are you usually using packages ?

There is a donation button, but it is forbidden to people who help me improve the software :)

**Comment by dahumph** [comment]
hi, just got back from holidays.
seems new version is not in the packages yet, at least for ARM?

**Comment by medoc92** [comment]
1.2.12 should be in the repo ? What system are you running exactly (debian or raspbian, jessie or wheezy) ?

**Comment by dahumph** [comment]
I'm using 8.0
so far I used this repo:

deb http://www.lesbonscomptes.com/upmpdcli/downloads/debian/ unstable main 
deb-src http://www.lesbonscomptes.com/upmpdcli/downloads/debian/ unstable main

and there it is still 1.2.11 version

the version from

deb http://www.lesbonscomptes.com/upmpdcli/downloads/raspbian-jessie/ unstable main 
deb-src http://www.lesbonscomptes.com/upmpdcli/downloads/raspbian-jessie/ unstable main

and

deb http://www.lesbonscomptes.com/upmpdcli/downloads/debian-jessie/ unstable main 
deb-src http://www.lesbonscomptes.com/upmpdcli/downloads/debian-jessie/ unstable main

is indicated to be 1.2.12, but crashes on my system (code=killed, signal=SEGV)

so, actually I'm not sure which repo is intended to use with my system right now...

**Comment by medoc92** [comment]
Please try again with the raspbian-jessie repo, but first remove the old packages and run apt-get clean to be sure that they are downloaded and installed again.

    sudo apt-get clean
    sudo apt-get update
    sudo apt-get remove upmpdcli
    sudo apt-get install sc2mpd upmpdcli upmpdcli-qobuz

I just checked that the upmpdcli 1.2.12  from raspbian-jessie runs fine on my rpi2

**Comment by dahumph** [comment]
did all steps...
`sudo service upmpdcli status
Main PID: 1050 (code=killed, signal=SEGV)

Jan 11 08:52:36 volumio systemd[1]: upmpdcli.service: main process exited, code=killed, status=11/SEGV
Jan 11 08:52:36 volumio systemd[1]: Unit upmpdcli.service entered failed state.`
Main PID: 1050 (code=killed, signal=SEGV)

**Comment by medoc92** [comment]
Maybe try to do the same with libupnpp3 (and even libupnp if it also comes from lesbonscomptes).

**Comment by dahumph** [comment]
that solved it! sorry for the trouble!
and works now perfect with kazoo, thank you, good app and great support!
