### ISSUE TITLE
pure virtual method called

### ISSUE THREAD

**Issue by sgraca** [medoc92/upmpdcli#69]
Hi,

I'm trying to setup upmpdcli on Raspberry Pi. I installed it from the package repository according to the instructions. My versions are:
```
upmpdcli -v
Upmpdcli 1.2.12 libupnpp 0.15.1
```

I use default configuration (no changes in /etc/upmpdcli.conf).

When I execute upmpdclli it fails with pure virtual method called error:
```
upmpdcli -l 6
:4:src/mpdcli.cxx:128::MPDCLi::openconn: mpd protocol version: 0.19.0
:4:libupnpp/upnpplib.cxx:155::LibUPnP: Using IP 192.168.1.8 port 49152
:5:src/httpfs.cxx:246::read_protocolinfo data: [http-get:*:application/flac:*,http-get:*:audio/flac:*,http-get:*:audio/x-flac:*,http-get:*:audio/aac:*,http-get:*:audio/x-aiff:*,http-get:*:audio/dff:*,http-get:*:audio/x-dff:*,http-get:*:audio/dsd:*,http-get:*:audio/x-dsd:*,http-get:*:audio/dsf:*,http-get:*:audio/x-dsf:*,http-get:*:audio/m4a:*,http-get:*:audio/x-m4a:*,http-get:*:audio/mp1:*,http-get:*:audio/mp4:*,http-get:*:audio/mpeg:*,http-get:*:audio/x-mpeg:*,http-get:*:audio/ogg:*,http-get:*:audio/vorbis:*,http-get:*:audio/wav:*,http-get:*:audio/x-wav:*,http-get:*:audio/wave:*,http-get:*:audio/x-ms-wma:*,http-get:*:audio/x-ogg:*,http-get:*:audio/x-scpls:*,http-get:*:audio/x-vorbis+ogg:*,http-get:*:audio/x-vorbis:*,http-get:*:video/mp4:*]
:4:src/httpfs.cxx:292::Failed reading /usr/share/upmpdcli/icon.png : open/stat: errno: 2 :
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:AVTransport]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:RenderingControl]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:ConnectionManager]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Info]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Time]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Volume]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Playlist]
pure virtual method called
terminate called without an active exception
Aborted
```

**Comment by medoc92** [comment]
Sebastian Graca writes:
 > Hi,
 > 
 > I'm trying to setup upmpdcli on Raspberry Pi. I installed it from the package
 > repository according to the instructions. My versions are:

What system are you running ? what exact source are you installing from ?

**Comment by sgraca** [comment]
I'm running OSMC 2016.12-1 for Raspberry 2/3 (https://osmc.tv/download/)

I installed upmpdcli using apt by setting up source for raspbian jessie (http://www.lesbonscomptes.com/upmpdcli/downloads/raspbian-jessie/ unstable main).

**Comment by medoc92** [comment]
I think OSMC is based on Debian, not Raspbian (I vaguely remember already seeing this issue, it was solved by recompiling last time).
Please try replacing raspbian-jessie with debian-jessie, deleting the package, and reinstalling.
Else you can try rebuilding from source: http://lesbonscomptes.com/upmpdcli/upmpdcli-debian-build.txt

**Comment by sgraca** [comment]
Reinstalling from using debian-jessie helped. Thank you.
