### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by mczerski** [medoc92/upmpdcli#70]
Hi,

I'm running upmpdcli 1.2.11-1 on CHIP board using debian jessie and kernel 4.4.13. Actually i'm not running it because it segfaults at startup.
If I run /usr/bin/upmpdcli -l 6 it segfaults in different places,  below are two examples:
`:4:src/mpdcli.cxx:128::MPDCLi::openconn: mpd protocol version: 0.19.0
:4:libupnpp/upnpplib.cxx:155::LibUPnP: Using IP 192.168.0.95 port 49152
:5:src/httpfs.cxx:246::read_protocolinfo data: [http-get:*:application/flac:*,http-get:*:audio/flac:*,http-get:*:audio/x-flac:*,http-get:*:audio/aac:*,http-get:*:audio/x-aiff:*,http-get:*:audio/dff:*,http-get:*:audio/x-dff:*,http-get:*:audio/dsd:*,http-get:*:audio/x-dsd:*,http-get:*:audio/dsf:*,http-get:*:audio/x-dsf:*,http-get:*:audio/m4a:*,http-get:*:audio/x-m4a:*,http-get:*:audio/mp1:*,http-get:*:audio/mp4:*,http-get:*:audio/mpeg:*,http-get:*:audio/x-mpeg:*,http-get:*:audio/ogg:*,http-get:*:audio/vorbis:*,http-get:*:audio/wav:*,http-get:*:audio/x-wav:*,http-get:*:audio/wave:*,http-get:*:audio/x-ms-wma:*,http-get:*:audio/x-ogg:*,http-get:*:audio/x-scpls:*,http-get:*:audio/x-vorbis+ogg:*,http-get:*:audio/x-vorbis:*,http-get:*:video/mp4:*]
:4:src/httpfs.cxx:292::Failed reading /usr/share/upmpdcli/icon.png : open/stat: errno: 2 : 
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:AVTransport]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:RenderingControl]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:ConnectionManager]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Info]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Time]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Volume]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Playlist]
:4:src/ohplaylist.cxx:107::ohPlaylist: cache restore done
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Radio]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:ProductSegmentation fault`

`:4:src/mpdcli.cxx:128::MPDCLi::openconn: mpd protocol version: 0.19.0
:4:libupnpp/upnpplib.cxx:155::LibUPnP: Using IP 192.168.0.95 port 49152
:5:src/httpfs.cxx:246::read_protocolinfo data: [http-get:*:application/flac:*,http-get:*:audio/flac:*,http-get:*:audio/x-flac:*,http-get:*:audio/aac:*,http-get:*:audio/x-aiff:*,http-get:*:audio/dff:*,http-get:*:audio/x-dff:*,http-get:*:audio/dsd:*,http-get:*:audio/x-dsd:*,http-get:*:audio/dsf:*,http-get:*:audio/x-dsf:*,http-get:*:audio/m4a:*,http-get:*:audio/x-m4a:*,http-get:*:audio/mp1:*,http-get:*:audio/mp4:*,http-get:*:audio/mpeg:*,http-get:*:audio/x-mpeg:*,http-get:*:audio/ogg:*,http-get:*:audio/vorbis:*,http-get:*:audio/wav:*,http-get:*:audio/x-wav:*,http-get:*:audio/wave:*,http-get:*:audio/x-ms-wma:*,http-get:*:audio/x-ogg:*,http-get:*:audio/x-scpls:*,http-get:*:audio/x-vorbis+ogg:*,http-get:*:audio/x-vorbis:*,http-get:*:video/mp4:*]
:4:src/httpfs.cxx:292::Failed reading /usr/share/upmpdcli/icon.png : open/stat: errno: 2 : 
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:AVTransport]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:RenderingControl]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:ConnectionManager]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Info]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Time]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Volume]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Playlist]
:4:src/ohplaylist.cxx:107::ohPlaylist: cache restore done
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Radio]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Product]
:4:src/ohproduct.cxx:103::OHProduct::OHProduct: sources: <SourceList>
 <Source>
  <Name>Playlist</Name>
  <Type>Playlist</Type>
  <Visible>1</Visible>
  </Source>
 <Source>
  <Name>Radio</Name>
  <Type>Radio</Type>
  <Visible>1</Visible>
  </Source>
</SourceList>

:4:src/main.cxx:702::Entering event loop
:4:src/main.cxx:709::Renderer event loop`

So I tried to run upmpdcli with strace to see what is happening and it does not crash ... so maybe it is some sort of race condition ?

**Comment by medoc92** [comment]
What repository did you install it from (contents of your apt sources please :) )

If you are running debian, not raspbian, you should be using 
   deb http://www.lesbonscomptes.com/upmpdcli/downloads/debian-jessie/ unstable main

*not" raspbian-jessie or simply 'debian' which is now a link to the wheezy version. I don't know why raspbian and debian are now incompatible but they most certainly are. If you got it wrong, you need to explicitely delete the libupnp, libupnpp3 and upmpdcli packages before reinstalling (use apt-get clean and apt-get remove).

**Comment by mczerski** [comment]
this is what I have in my apt sources:
deb http://www.lesbonscomptes.com/upmpdcli/downloads/debian/ unstable main

apt-cache policy upmpdcli
upmpdcli:
  Installed: 1.2.11-1
  Candidate: 1.2.11-1
  Version table:
 *** 1.2.11-1 0
        500 http://www.lesbonscomptes.com/upmpdcli/downloads/debian/ unstable/main armhf Packages
        100 /var/lib/dpkg/status

apt-cache policy libupnpp3
libupnpp3:
  Installed: 0.15.1-1
  Candidate: 0.15.1-1
  Version table:
 *** 0.15.1-1 0
        500 http://www.lesbonscomptes.com/upmpdcli/downloads/debian/ unstable/main armhf Packages
        100 /var/lib/dpkg/status

**Comment by mczerski** [comment]
ach ok, debian not debian-jessie :)

**Comment by mczerski** [comment]
I used http://www.lesbonscomptes.com/upmpdcli/downloads/debian-jessie/ source and it works, thanks !
