### ISSUE TITLE
Qobuz showing only 49 albums in favorites

### ISSUE THREAD

**Issue by volkma** [medoc92/upmpdcli#72]
I'm using the latest version of upmpdcli + upmpdcli-qobuz together with BubbleUpnP or Linn Kazoo.
When i browse my Qobuz-Favorites, I can see only the latest 49 albums. Is this something i can configure or a Qobuz web-api limitation?
Regards
Volkmar

**Comment by medoc92** [comment]
This was a bug in the upmpdcli plugin ("49 entries should be enough for anybody" :) )

This should be corrected in the current git code. You can get it by replacing the file /usr/share/upmpdcli/cdplugins/qobuz/session.py with this one:

https://raw.githubusercontent.com/medoc92/upmpdcli/master/src/mediaserver/cdplugins/qobuz/session.py
