### ISSUE TITLE
Tidal integration

### ISSUE THREAD

**Issue by lambrusco** [medoc92/upmpdcli#73]
Hi, I saw that the Tidal integration used the first kodi-tidal plugin which seems abandoned,
I see that there's a fork of that project which also seems to support the new master audio streams:
https://github.com/arnesongit/plugin.audio.tidal2

Have you already looked at it?
May I try to integrate it? In case I probably would need support for the bridge between upmpdcli and the python script.

Thanks

**Comment by medoc92** [comment]
Yes, sure, you can have a look. The interface with upmpdcli is very simple and all in the tidal-app.py script, don't hesitate to ask if you have an issue.

As far as I can see MQA is marketing crap with a side objective of hurting the open formats (FLAC, MP3) and reintroducing DRM of some kind or other. Not moving a finger to help with this aspect.

**Comment by lambrusco** [comment]
Sure, I'm not a fan of DRM too, I was thinking that Master was just 24bit/96Khz, anyway I'll try to integrate the new version, check this part and I will let you know!

**Comment by medoc92** [comment]
Closing this because it seems inactive. Please don't hesitate to reopen if there is movement...
