### ISSUE TITLE
artScript and OpenHome CPs

### ISSUE THREAD

**Issue by distler** [medoc92/upmpdcli#74]
I've been attempting to try out the new `artScript` feature for web radios.

* I have an executable (a ruby script, but that shouldn't matter) in `/usr/local/bin/` with the correct (755) permissions.
* I've verified that executing it spits out the correct URL for the artwork of the song currently being played.
* I've verified that the resource at that URL (an `https://` URL, in case that matters) is retrievable both in a web browser and using `wget`.

But neither Lumin.app nor Linn Kazoo display anything for the artwork of the currently-playing song. (They do display the image at `artUrl` as the artwork associated to the radio station. But the artwork associated to the playing song is blank.)

Is there a commandline (or other) tool that I could use to see whether the `artScript` output is being transmitted to the CP?

**Comment by medoc92** [comment]
Actually, I think that very few Control Points expect the Radio art to change.

You can test your script with Upplay, I just checked that it displays the current song art.

Actually, after having had a look at it, I think that I don't update the art URI in all places where it should appear (the art link is set in the data returned by Info command, but not in the currently playing radio, where it is empty, which explains why you have no logo at all probably). I'll take a better look at this tomorrow.

**Comment by medoc92** [comment]
After checking: I'm afraid that upplay is currently the only renderer supporting dynamic art for the current radio song. We had talked with the Bubble UPnP developper about his supporting this, but it appears that he had more urgent things to do (which I understand as upmpdcli is also the only renderer to support this as far as I know...). It's a very simple thing to do for the CP, but I guess that chicken and egg and all that...

**Comment by distler** [comment]
Hmm. Curious.

Lumin.app *almost* seems to be trying to do the right thing. Each time the song changes (as the new song title appears), there's a brief flash as the `artUrl` artwork is displayed and then goes blank. The point is that this happens *each time* the song changes -- which seems to indicate that Lumin.app is trying to update the artwork along with the song title.

But thanks for checking ... Evidently, this is a CP problem, not a `upmpdcli` bug.

**Comment by medoc92** [comment]
It's strange that Lumin goes back to blank... I could understand if it went back to displaying the static Radio logo, but blank is weird. Did you set the artUrl parameter to the static radio logo ?

**Comment by distler** [comment]
> Did you set the artUrl parameter to the static radio logo ?

Correct.

* `artUrl` displays as the radio station logo in the list of stations.
* It flashes onscreen each time  the song changes (and then goes to blank) in the "Now Playing" view.
* And (something I just noticed): during a station break (the song-title is set to the station name and the `artScript` program returns nothing), the `artUrl` *stays* onscreen in the "Now Playing" view.

What does `upmpdcli` send when `artScript` returns nothing? Clearly Lumin behaves differently in that case.

**Comment by medoc92** [comment]
I think that if the script succeeds but returns nothing, the dynamic image becomes empty. If the script fails, the image is not set (retains its previous value which is initially the static one). Actually, I think that I should change this to set the dynamic image to the static one if the script fails or returns an empty value.

None of this seems to explain why the image goes away. Maybe you could try to return the static radio logo from the script just to see what happens then (in case there is something Lumin does not like with the real ones).

.

**Comment by distler** [comment]
I've tried that. Has no effect.

Actually, on closer examination, I can achieve the same effect by putting the iDevice to sleep and waking it back up (in the middle of a song). The `artUrl` image is displayed alongside the radio station name. After a second, the radio station name is replaced by the name of the currently-playing song, and the `artUrl` is replaced by a blank.

Presumably what I was seeing above was Lumin using the `artUrl` as a placeholder while it was updating the current song information (when the song changes). Logically, the only reason to do that would be if it *expected* to be able to replace `artUrl` with a more appropriate image after obtaining the updated song information.

That's what led me to think that it supports (something like) this feature. But who knows what they've actually implemented ...

**Comment by medoc92** [comment]
this would seem to indicate that Lumin is indeed expecting dynamic information, but that it's getting it from an interface where it is not set. I can think of at least 3 ways it can get the info, maybe I am forgetting one, I am going to check.

**Comment by medoc92** [comment]
I've found another place where I could set the current track art uri, and this seems to have done the trick with Kazoo (a slightly outdated version on win10, I've failed updating to the latest).

Can you easily build from git code ? (meaning, are you already set up for this, don't lose your time).
Else I'll build a package on the Launchpad 'experimental' upmpdcli repo.

**Comment by distler** [comment]
>Can you easily build from git code?

I'll have to install the development tools. (Volumio2, which is the distro I'm using, has Git, but none of the other developer tools installed. I used `apt-get` to update `upmpdcli` to version 1.2.12-1.)

**Comment by medoc92** [comment]
Ok, don't lose your time, I'm already setup for this, I'll build a package.

**Comment by medoc92** [comment]
OOps question: do you use the raspbian or vanilla debian apt  repository on lesbonscomptes ?

**Comment by distler** [comment]
raspbian.

**Comment by medoc92** [comment]
So I have uploaded a new upmpdcli package. It's versionned 1.2.13, but beware that that's not what the real 1.2.13 will be, so you'll have to remember to remove this one (dpkg -r) when the real 1.2.13 comes out:

http://lesbonscomptes.com/upmpdcli/files/upmpdcli_1.2.13-1_armhf.deb

**Comment by distler** [comment]
OK. Will try it out tonight.

**Comment by medoc92** [comment]
Hopefully I did not mess up with the package build. Every time I stop for a few weeks, I forget everything about this stuff :)

**Comment by distler** [comment]
Works brilliantly, now. Both in Lumin and in Linn Kazoo.

Thank you!!

**Comment by medoc92** [comment]
Thanks for your help for fixing this !
