### ISSUE TITLE
Not visible for clients

### ISSUE THREAD

**Issue by godcore** [medoc92/upmpdcli#75]
Hello

I'm trying to setup upmpdcli with mopidy on RasPI 3. Mopidy works fine but upmpdcli is not discoverable in its own network for UPnP clients (e.g. Bubble UPnP for Android), although I don't see anything weird in logs:

```
$ tail -n 50 /var/log/upmpdcli.log
:4:src/mpdcli.cxx:128::MPDCLi::openconn: mpd protocol version: 0.19.0
:4:libupnpp/upnpplib.cxx:155::LibUPnP: Using IP 192.168.0.200 port 49152
:5:src/httpfs.cxx:246::read_protocolinfo data: [http-get:*:application/flac:*,http-get:*:audio/flac:*,http-get:*:audio/x-flac:*,http-get:*:audio/aac:*,http-get:*:audio/x-aiff:*,http-get:*:audio/dff:*,http-get:*:audio/x-dff:*,http-get:*:audio/dsd:*,http-get:*:audio/x-dsd:*,http-get:*:audio/dsf:*,http-get:*:audio/x-dsf:*,http-get:*:audio/m4a:*,http-get:*:audio/x-m4a:*,http-get:*:audio/mp1:*,http-get:*:audio/mp4:*,http-get:*:audio/mpeg:*,http-get:*:audio/x-mpeg:*,http-get:*:audio/ogg:*,http-get:*:audio/vorbis:*,http-get:*:audio/wav:*,http-get:*:audio/x-wav:*,http-get:*:audio/wave:*,http-get:*:audio/x-ms-wma:*,http-get:*:audio/x-ogg:*,http-get:*:audio/x-scpls:*,http-get:*:audio/x-vorbis+ogg:*,http-get:*:audio/x-vorbis:*,http-get:*:video/mp4:*]
:4:src/httpfs.cxx:292::Failed reading /usr/share/upmpdcli/icon.png : open/stat: errno: 2 :
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:AVTransport]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:RenderingControl]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:ConnectionManager]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Info]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Time]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Volume]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Playlist]
:4:src/ohplaylist.cxx:107::ohPlaylist: cache restore done
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Radio]
:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Product]
:4:src/ohproduct.cxx:103::OHProduct::OHProduct: sources: <SourceList>
 <Source>
  <Name>Playlist</Name>
  <Type>Playlist</Type>
  <Visible>1</Visible>
  </Source>
 <Source>
  <Name>Radio</Name>
  <Type>Radio</Type>
  <Visible>1</Visible>
  </Source>
</SourceList>

:4:src/main.cxx:702::Entering event loop
:4:src/main.cxx:709::Renderer event loop
:4:src/mpdcli.cxx:809::MPDCli::getQueueData
:4:src/mpdcli.cxx:794::MPDCli::getQueueSongs: 0 songs
:4:src/ohplaylist.cxx:146::OHPlaylist::translateIdArray: current ids:
```

```
$ sudo netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 192.168.0.200:49152     0.0.0.0:*               LISTEN      1163/upmpdcli
```

I use latest version `1.2.12`. Thanx in advance

**Comment by medoc92** [comment]
Everything looks normal, so this is likely a network issue. 

- If the machine has several interfaces, specify the right one (either as ip or device in /etc/upmpdcli.conf). For example, something like:

     upnpiface = eth0

Or
    upnpip = 192.168.x.y

"ip addr" will show you interfaces and addresses.

If there is only one interface, maybe try disabling the firewall if it is running ?

**Comment by godcore** [comment]
I've tried both cases and now my config looks like: 

```
logfilename = /var/log/upmpdcli.log
loglevel = 5
mpdhost = ::ffff:0.0.0.0
upnpip = 192.168.0.200
```
btw, upmpdcli couldn't connect to mopidy until I specified mpdhost like that. Can this affect smth?

I didn't configure firewall, this is clean installed Jessie on PI and I'm even able to connect to `49152` via browser getting 500 Internal server error. I guess it's normal

**Comment by medoc92** [comment]
It's weird that you have to set the mpdhost parameter if both processes are running on the same machine (it defaults to localhost), and even weirder that you have to use an ipv6 address. Maybe there is an issue with the localhost setup. Here follows what a default /etc/hosts file looks like:

    127.0.0.1	localhost
    ::1		localhost ip6-localhost ip6-loopback
    ff02::1		ip6-allnodes
    ff02::2		ip6-allrouters
    
    127.0.1.1	rasp20

(rasp20 is the host name).

Are you using wifi or a wired connection.

UPnP discovery needs SSDP to work, in addition to the TCP connections to 4915x. SSDP uses multicast on address 239.255.255.250

See this page for more details on SSDP:
https://en.wikipedia.org/wiki/Simple_Service_Discovery_Protocol

I'm not too sure what may be happening. This usually "just works" (except sometimes when there are multiple interfaces). The mpdhost thing does seem weird, and should be investigated (localhost should work).

**Comment by medoc92** [comment]
Mysterious and no feedback

**Comment by godcore** [comment]
Sorry for a silence. Unfortunately, I have no time for deeper investigation right now. It really looks like a problem is with some other components. I'll contact you if I find the reason
