### ISSUE TITLE
Pure virtual method called

### ISSUE THREAD

**Issue by halloamt** [medoc92/upmpdcli#76]
Hi,

first, merci pour cette programme :-) Mais si je ne parle pas français j'ecrire en anglais.
I tried updated upmpdcli just now and used the new configuration file with some changes. Now it won't start and aborts with a "call to pure virtual method". I tried installing the three plugins but that did not help. I'm running it on Raspbian. 

Greetings :-)

`root@wohnzimmer:~# uname -a`
`Linux wohnzimmer 4.4.38-v7+ #938 SMP Thu Dec 15 15:22:21 GMT 2016 armv7l GNU/Linux`
`root@wohnzimmer:~# cat /etc/debian_version`
`8.0`
`root@wohnzimmer:~# upmpdcli -c /etc/upmpdcli.conf -l 6`
`:4:src/mpdcli.cxx:128::MPDCLi::openconn: mpd protocol version: 0.19.0`
`:4:libupnpp/upnpplib.cxx:155::LibUPnP: Using IP 192.168.207.240 port 49152`
`:5:src/httpfs.cxx:246::read_protocolinfo data: [http-get:*:application/flac:*,http-get:*:audio/flac:*,http-get:*:audio/x-flac:*,http-get:*:audio/aac:*,http-get:*:audio/x-aiff:*,http-get:*:audio/dff:*,http-get:*:audio/x-dff:*,http-get:*:audio/dsd:*,http-get:*:audio/x-dsd:*,http-get:*:audio/dsf:*,http-get:*:audio/x-dsf:*,http-get:*:audio/m4a:*,http-get:*:audio/x-m4a:*,http-get:*:audio/mp1:*,http-get:*:audio/mp4:*,http-get:*:audio/mpeg:*,http-get:*:audio/x-mpeg:*,http-get:*:audio/ogg:*,http-get:*:audio/vorbis:*,http-get:*:audio/wav:*,http-get:*:audio/x-wav:*,http-get:*:audio/wave:*,http-get:*:audio/x-ms-wma:*,http-get:*:audio/x-ogg:*,http-get:*:audio/x-scpls:*,http-get:*:audio/x-vorbis+ogg:*,http-get:*:audio/x-vorbis:*,http-get:*:video/mp4:*]`
`:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:AVTransport]`
`:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:RenderingControl]`
`:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:upnp-org:serviceId:ConnectionManager]`
`:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Info]`
`:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Time]`
`:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Volume]`
`:4:libupnpp/device/device.cxx:423::UpnpDevice::addService: [urn:av-openhome-org:serviceId:Playlist]`
`pure virtual method called`
`terminate called without an active exception`
`Aborted`
`root@wohnzimmer:~#`

**Comment by halloamt** [comment]
P.S.: It works woth openhome = 0

**Comment by medoc92** [comment]
This is quite typical of using a version compiled for the wrong OS. It seems that you are running raspbian jessie, so you should have the following in your sources list (note: raspbian-jessie, not debian as in the old links):

    deb http://www.lesbonscomptes.com/upmpdcli/downloads/raspbian-jessie/ unstable main 
    deb-src http://www.lesbonscomptes.com/upmpdcli/downloads/raspbian-jessie/ unstable main

http://lesbonscomptes.com/upmpdcli/downloads.html

You may need to remove the packages (upmpdcli and libupnpp3) first in order to force the change.

**Comment by halloamt** [comment]
Works, Thanks :-)
