### ISSUE TITLE
upmpdcli aborted (pure virtual method called)

### ISSUE THREAD

**Issue by dony71** [medoc92/upmpdcli#82]
Already follow this link https://github.com/medoc92/upmpdcli/issues/76 but upmpdcli cannot start immediately
I set upmpdcli automatically restart systemv using monit (https://mmonit.com/monit/)
eventually it will work after couple times restart (not sure how many times)
Run directly from console always fails
Platform BananaPi (armv7 RPi like) under armbian OS based on debian jessie (https://www.armbian.com)

~# upmpdcli -c /etc/upmpdcli.conf
pure virtual method called
terminate called without an active exception
Aborted

**Comment by medoc92** [comment]
Please try to uninstall the package:

    sudo apt-get remove upmpdcli libupnpp3

then check that your /etc/apt/sources.list.d/upmpdcli point to debian-jessie NOT raspbian-jessie:

    deb http://www.lesbonscomptes.com/upmpdcli/downloads/debian-jessie/ unstable main 
    deb-src http://www.lesbonscomptes.com/upmpdcli/downloads/debian-jessie/ unstable main

then:

    sudo apt-get update
    sudo apt-get install upmpdcli

**Comment by dony71** [comment]
thanks
seems like working stable now
