### ISSUE TITLE
Google Music auth with 2 factor authentication

### ISSUE THREAD

**Issue by PhyberApex** [medoc92/upmpdcli#87]
I don't think it's currently possible to authenticate with the google music service if you have 2 factor authentication enabled. I would rather not disable this additional security feature.

Think you can implement the authentication with google in an oauth way?

~Cheers

**Comment by medoc92** [comment]
I knew this would come up one day :) This is a very valid request, but I don't have the time to look at this right now (and I don't have gmusic account any more). If you feel like giving it a try, that's great, else it will have to wait a bit.

**Comment by bubbleguuum** [comment]
@PhyberApex 

You can simply use a specific app password that you generate for upmpdcli:
https://support.google.com/accounts/answer/185833?hl=en

app passwords purpose is precisely to be able to login to Google for apps not supporting 2-step auth.

Now, the ability to authenticate in a web browser not requiring giving any login/password to the app is something else entirely.

**Comment by PhyberApex** [comment]
Oh I did not know those were still a thing. Thanks for letting me know! Now I can enjoy my google music over upmpdcli :)

~Cheers

**Comment by medoc92** [comment]
I am linking this from the manual and closing the issue.
