### ISSUE TITLE
upmpdcli has been added to the OpenWRT packages repository

### ISSUE THREAD

**Issue by ignisf** [medoc92/upmpdcli#9]
Just FYI

https://github.com/openwrt/packages/pull/624
https://github.com/openwrt/packages/pull/625

**Comment by medoc92** [comment]
Thanks !

**Comment by schmurtzm** [comment]
Hi,
upmpdcli and MPD are very nice ! When will it be upgraded for openWRT ?
The next versions offers good stuffs like web radios !
It is not up to date in the developpement branch of openwrt.
I use the 0.9 version every day thanks for that !

**Comment by ignisf** [comment]
Hi, @schmurtzm and thanks,

I currently can't test the package (out of the country) so I'm avoiding submitting an update. Feel free to submit a PR to update it if you can test it, it's actually quite simple and the nice people like @medoc92 and @thess are very helpful if you get stuck! :)
