### ISSUE TITLE
Build error after latest commit

### ISSUE THREAD

**Issue by espakman** [medoc92/upmpdcli#90]
Hi,

After the latest commit I get the following build error:

src/execmd-fixed.cpp: In member function ‘int ExecCmd::startExec(const string&, const std::vector<std::__cxx11::basic_string<char> >&, bool, bool)’:src/execmd-fixed.cpp:531:56: error: ‘strcpy’ was not declared in this scope         strcpy(cp, (it.first + "=" + it.second).c_str());                                                           ^
make[1]: *** [Makefile:791: src/execmd-fixed.o] Error 1
make[1]: Leaving directory '/home/espakman/packages/upmpdcli-archphile/src/upmpdcli'
make: *** [Makefile:528: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

**Comment by serverbaboon** [comment]
Same error for me.

**Comment by medoc92** [comment]
I had forgotten to commit a change. It should be fixed now.
