### ISSUE TITLE
qobuz interface

### ISSUE THREAD

**Issue by nicolabotta** [medoc92/upmpdcli#91]
Replay works fine but **search** seems to be **broken** with Kazoo 4.11.226.0 running on Android 7.1.2. 

A search for "tarkovsky" in the **qobuz app**, for instance, yields "Tarkovsky Quartet" as the second entry of the auto suggested list of results after entering just "tarko". A search with "tarkovsky" yields "Tarkovsky Quartet" as the first entry in a breeze.

In the **upmpdcli interface**, searching is extremely slow. A search with "tarkovsky" takes about 15 seconds and yields a list of results that does **not** contain "Tarkovsky Quartet"! The first entry is "Gabor Tarkovi".

**Comment by serverbaboon** [comment]
Is this a search for an Artist or Album?

As far as Artists go upmpdcli brings back the same results as the Bubble Qobuz interface (only a a lower specified count).

If you are talking album I can see there is a Tarkovsky Quartet by Francois Couturier that is not not returned.

**Comment by serverbaboon** [comment]
Actually just checked my Qobuz app and it did not return an artist either so you are meaning Album?

**Comment by serverbaboon** [comment]
Trying to put off mowing the lawn so had a quick look at this.

I cannot comment on the speed but maybe multiple searches are being performed, one against album, then track etc, JF can correct me on that.

Looking at the source code It looks like upmpdcli filters out the albums that are not available to play, checking in the Qobuz App confirms that Tarkosky Quartet  by Francois Couturier is not available (except for 20 extract) as restricted by rights holder. Bubble also displays a message about only being able to play an extract.

**Comment by nicolabotta** [comment]
@serverbaboon You are right, that's likely the reason why Tarkovsky Quartet is not displayed. The Tarkovsky Quartet albums can only be streamed if one buys them. Since the upmpdcli interface does not anyway support access to albums that have been bought, it make sense not to display the results. Thus, I am going to close the issue. Thanks for your ready support! Best, Nicola

**Comment by medoc92** [comment]
Hi.

I am re-opening this, because I need to check why the qobuz search is so slow. @serverbaboon is right that multiple qobuz searches are being performed, but still.

@nicolabotta : I guess that you are using Kazoo with a Linn renderer ? I have one around so I can set up the qobuz interface and have a look at the differences.

I am quite open to suggestions about how all this could be improved. Should I show the '20S extract' tracks ? Other ideas ?

**Comment by nicolabotta** [comment]
@medoc92 "I guess that you are using Kazoo with a Linn renderer ?" No, I am using Kazoo 4.11.226.0 (on a Nexus 5X running Android 7.1.2) with upmpdcli. I have compared the search function made available by upmpdcli-qobuz with the search function implemented in the qobuz app 3.2.2.21

**Comment by medoc92** [comment]
Thanks, ok, got it now.

**Comment by medoc92** [comment]
A recent commit reduced the number of requests sent to the qobuz service during a search. Things are now faster (but still slow...).
