### ISSUE TITLE
Qobuz formatid for HiRes

### ISSUE THREAD

**Issue by dahumph** [medoc92/upmpdcli#92]
Hi,
wondering if the qobuz plugin is already capable of streaming Hi-Res audio beyond 44,1khz. If so, what would be the formatid in the config file?

thanks...

**Comment by medoc92** [comment]
It seems that qobuzformatid = 5 yields mp3, 7 would be for FLAC

I have not tested hi-res. The format ids seem to be described here: https://github.com/Qobuz/api-documentation#hi-res-in-api

I am not sure that the current module does everything necessary for the hi-res files, but maybe you can experiment ?

**Comment by dahumph** [comment]
to whom it may concern...

after having a closer look, streaming beyond 44,1khz flac for the time seems to be not possible. qobuz presently does allow streaming in higher resolution only for purchased albums, which are listed in a dedicated "folder". and as far as i can see, one can only stream hi-res flac out of this folder, but not exactly the same item from the regular qobuz streaming database. so as long as the plugin does not list this folder, hi-res streaming will not work. however, qobuz has announced a new service, which allows everything out of their database to be streamed in hi-res beyond 44,1khz, not only purchased albums. will be interesting to see if this works with the qobuz-plugin. maybe someone with the sublime+ service wants to share his experience with this?
