### ISSUE TITLE
upmpdcli songcast sender and kazoo

### ISSUE THREAD

**Issue by medoc92** [medoc92/upmpdcli#93]
Unable to control the upmpdcli Songcast functions from Kazoo.

There are differences about how an actual Linn device and upmpdcli behave relating to Songcast. For example, the Linn device has a Receiver source which becomes active when linked.

If the Linn Receiver source is selected in Upplay (no idea what this does as there is no way to select the Sender this way), the Receiver disappears from the upplay Songcast tool.

Elucidating these differences may help explain why things do not work with Kazoo currently.

**Comment by joerg-krause** [comment]
My guess is that Kazoo uses the ohSongcast implementation from the [ohPipeline](https://github.com/openhome/ohPipeline/tree/master/OpenHome/Av/Songcast) repo. The [ohSongcast](https://github.com/openhome/ohSongcast) repo is unmaintened.

**Comment by medoc92** [comment]
@joerg-krause Thanks for pointing this out. Actually there is something in the latest commits in https://github.com/openhome/ohPipeline/tree/master/OpenHome/Av/Songcast about making the Sender conform to the spec, then reverting the change for Kazoo compat.

I need to revisit the whole thing. Could you please point me to your  current build script for OpenHome if you have one somewhere?

**Comment by joerg-krause** [comment]
I'm using my own Buildroot branch for building some of the OpenHome packages: https://github.com/joerg-krause/buildroot/tree/oh.

**Comment by medoc92** [comment]
Thanks! I will take a look and go from there to update the general build.

**Comment by joerg-krause** [comment]
You're welcome! If you need any help, please feel free to ask.

**Comment by medoc92** [comment]
Upmpdcli 1.2.14 fixes the issue of upmpdcli Receiver visibility in Kazoo. Upmpdcli Receivers can now be grouped from Kazoo.

Upmpdcli Senders are unusable from Kazoo (4.11.226), reason unknown. Use Bubble or Upplay.
