### ISSUE TITLE
ImportError: No module named gmusicapi

### ISSUE THREAD

**Issue by GourouLubrik** [medoc92/upmpdcli#95]
I've two installation of upmpdcli on two different plateform (armbian for cubietruck / ubuntu 16.04.2) that have that bug. 

Here's the relevant log trace of my ubuntu, installed through the PPA, along with upmpdcli-gmusic and upmpdcli-qobuz packages.

> 4:src/mediaserver/contentdirectory.cxx:288::ContentDirectory::actBrowse:  ObjectID 0$gmusic$ BrowseFlag BrowseDirectChildren Filter * StartingIndex 0 RequestedCount 1000 SortCriteria 
> :4:src/mediaserver/contentdirectory.cxx:55::ContentDirectory::pluginFactory: for gmusic
> :4:src/mediaserver/contentdirectory.cxx:69::ContentDirectory: host 192.168.1.60 port 49152
> :4:src/mediaserver/cdplugins/plgwithslave.cxx:199::PlgWithSlave: starting httpd on port 49149
> :4:src/mediaserver/cdplugins/cmdtalk-fixed.cpp:62::CmdTalk::startCmd
> :4:src/execmd-fixed.cpp:454::ExecCmd::startExec: (1|1) /usr/share/upmpdcli/cdplugins/gmusic/gmusic-app.py 
> :5:src/mediaserver/cdplugins/plgwithslave.cxx:425::ContentCache::get: not found gmusic:0$gmusic$
> Traceback (most recent call last):
>   File "/usr/share/upmpdcli/cdplugins/gmusic/gmusic-app.py", line 38, in <module>
>     from session import Session
>   File "/usr/share/upmpdcli/cdplugins/gmusic/session.py", line 25, in <module>
>     from gmusicapi import Mobileclient
> ImportError: No module named gmusicapi
> :4:src/execmd-fixed.cpp:901::ExecCmd::getline: got 0
> :2:src/mediaserver/cdplugins/cmdtalk-fixed.cpp:101::CmdTalk: getline error
> :4:src/execmd-fixed.cpp:274::ExecCmd: killpg(33883, SIGTERM)
> :2:src/mediaserver/cdplugins/plgwithslave.cxx:489::PlgWithSlave::browse: slave failure

I really love the "new" fonctionnality of mediaserver. And I hope that can be fixed.
Many thanks for your excellent work.

**Comment by medoc92** [comment]
You need to install gmusicapi, it's not in the repos, so it can't be an automatic dependancy. 

    sudo pip install gmusicapi

should do it (pip itself is in the repos if it's not already installed).

**Comment by GourouLubrik** [comment]
I feel very bad about opening a non-existing doc. I've badly read the docs. 👎 

Now it's working (at least on ubuntu, my armbian pip doesn't work)

I've now have a bug in the google music upnp tree, I can see the playlist, their name, but they're empty.

Where is the donate button ? I can't find it (even with a google search)

**Comment by medoc92** [comment]
No problem about missing the gmusicapi dep, nobody reads the docs :)

You should be able to install gmusicapi by building it locally, without using pip., 
https://github.com/simon-weber/gmusicapi.git

    python setup.py build
    sudo python setup.py install

I don't seem to have a problem with playlists. I am not a big gmusic user though, I just have a test one. Could you point me to a playlist you have trouble with ?

About donations: really, don't feel obliged. But I do have a donations page: https://www.lesbonscomptes.com/donations/index.html
It's difficult to find because it's mainly targeted at MS Windows users (rationale: I hate Windows development), with whom I have little success anyway :)

**Comment by medoc92** [comment]
Hi, 

I am opening another issue for the playlist thing. Will be clearer. Please comment there.
