### ISSUE TITLE
Enable ape file format

### ISSUE THREAD

**Issue by parkmino** [medoc92/upmpdcli#96]
Please add appropriate line(s) in protocolinfo.txt.
Some people play those kind of songs.

Thanks in advance

**Comment by medoc92** [comment]
I certainly can do this. What is the MIME type used by Media Servers for this ?

**Comment by parkmino** [comment]
I added 'audio/x-ape' and it works.
I googled and some said 'audio/x-monkeys-audio' is more correct.

**Comment by medoc92** [comment]
Thanks, I'll add both, can't hurt... Just pushed the new protocolinfo.txt
