### ISSUE TITLE
Gmusic: some playlists are seen as empty.

### ISSUE THREAD

**Issue by medoc92** [medoc92/upmpdcli#97]
Initially reported in issue #95

**Comment by GourouLubrik** [comment]
I've 3 playlists in my google music,, but none of them show their content in the upmpcli mediaserver.

this log is the result of selecting the library/playlist and then selecting a playlist in my upnp browser.
I've tested with two different upnp browser (foobar2000 and bubbleupnp) with the same log results.

I tried to make a playlist public to see if it could help. but it did not.

```
:4:src/mediaserver/contentdirectory.cxx:288::ContentDirectory::actBrowse:  ObjectID 0$gmusic$/user_playlists BrowseFlag BrowseDirectChildren Filter * StartingIndex 0 RequestedCount 1000 SortCriteria 
:5:src/mediaserver/cdplugins/plgwithslave.cxx:425::ContentCache::get: not found gmusic:0$gmusic$/user_playlists
:4:src/mediaserver/cdplugins/cmdtalk-fixed.cpp:109::CmdTalk: Got empty line
:5:src/mediaserver/cdplugins/plgwithslave.cxx:292::PlgWithSlave::results: got 3 entries 
:5:src/mediaserver/cdplugins/plgwithslave.cxx:431::ContentCache::set: gmusic:0$gmusic$/user_playlists
:5:src/mediaserver/cdplugins/plgwithslave.cxx:361::searchCacheEntryToResult: filter  start 0 cnt 1000 res.size 3
:4:libupnpp/device/device.cxx:318::UPNP_CONTROL_ACTION_REQUEST: Browse. Params: <?xml version="1.0"?>
<u:Browse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1">
<ObjectID>0$gmusic$/playlist/c7d93559-d26d-461b-8018-6ab273b5c0c3</ObjectID>
<BrowseFlag>BrowseDirectChildren</BrowseFlag>
<Filter>*</Filter>
<StartingIndex>0</StartingIndex>
<RequestedCount>1000</RequestedCount>
<SortCriteria></SortCriteria>
</u:Browse>

:4:src/mediaserver/contentdirectory.cxx:288::ContentDirectory::actBrowse:  ObjectID 0$gmusic$/playlist/c7d93559-d26d-461b-8018-6ab273b5c0c3 BrowseFlag BrowseDirectChildren Filter * StartingIndex 0 RequestedCount 1000 SortCriteria 
:5:src/mediaserver/cdplugins/plgwithslave.cxx:425::ContentCache::get: not found gmusic:0$gmusic$/playlist/c7d93559-d26d-461b-8018-6ab273b5c0c3
:4:src/mediaserver/cdplugins/cmdtalk-fixed.cpp:109::CmdTalk: Got empty line
:5:src/mediaserver/cdplugins/plgwithslave.cxx:292::PlgWithSlave::results: got 0 entries 
:5:src/mediaserver/cdplugins/plgwithslave.cxx:431::ContentCache::set: gmusic:0$gmusic$/playlist/c7d93559-d26d-461b-8018-6ab273b5c0c3
:5:src/mediaserver/cdplugins/plgwithslave.cxx:361::searchCacheEntryToResult: filter  start 0 cnt 1000 res.size 0

```

**Comment by medoc92** [comment]
Thanks for the trace. Unfortunately we are missing the potentially interesting part, which is the python module output (which goes to stderr). If you are on a systemd-based system, you can see it with journalctl -u upmpdcli -f (the -f is like tail -f). If not, you need to stop upmpdcli and re-start it in a console window.

Also, is there a way to share playlists (I'm really a gmusic noobs) ? I could try with one of yours.

**Comment by GourouLubrik** [comment]
Tried the systemctl, and as I'm a dev believing in voodoo magic, launching command line with redirecting stderr to stdout ( 2>1 ). But it appears to be no "real" error.

I could capture network traffic, but I guess it's waste of time as it's probably all encrypted into https.
is it possible to increase verbosity in gmusicapi.py so we can see what each request raw results ?

I can share the playlists making them public playlist, but I guess it's no use if you don't have an account ?
Also, upmpdcli won't access to another user shared playlist ?

**Comment by medoc92** [comment]
It would rather be 2>&1 to redirect :) Can I have a look at the log anyway. You can email it to me at jf@dockes.org.

I do have an account currently, for a few weeks, I had to renew my subscription for solving another issue, so, yes, if you can point me to the lists, it will help (I have no idea how to find a list by the way. Maybe search by it's name? Make it original :) )

**Comment by medoc92** [comment]
Feel free to reopen when you can give me some feedback. At this point, I can't reproduce the issue, so I can't fix it.
