### ISSUE TITLE
Wavpack support needed

### ISSUE THREAD

**Issue by harbinbeer** [medoc92/upmpdcli#98]
`:2:src/upmpd.cxx:156::checkContentFormat: unsupported:: audio/x-wavpack`

Thank you.

**Comment by medoc92** [comment]
Could you please try to either add the following to /etc/upmpdcli.conf:

    checkcontentformat = 0

Or add the following line to /usr/share/upmpdcli/protocolinfo.txt:

    http-get:*:audio/x-wavpack:*,

Then restart upmpdcli and check that things work.

If they do, I'll add the line to the distributed protocolinfo.txt

**Comment by harbinbeer** [comment]
It works.
THX!

**Comment by medoc92** [comment]
Thanks, I committed the change.
