### ISSUE TITLE
Kazoo grouping of receivers

### ISSUE THREAD

**Issue by espakman** [medoc92/upmpdcli#99]
Although it's possible now after commit 8b180f49e2c018c9cd5bf61a96343b3a3ad1f844 to group different receivers in Kazoo it crashes IOS Kazoo when actually selecting the receiver to connect with. In Windows 10 Kazoo doesn't crash, but the selection is not persistent.

upmpdcli, libupnpp, sc2mpd git versions from may 25

**Comment by medoc92** [comment]
I also see the not-persistent selection on windows (only on the UI, the receiver stays connected all right).

I think that you should report these to the Kazoo developpers. I am quite willing to fix what needs fixing, but I have no idea what it is.

**Comment by medoc92** [comment]
Need input from a Kazoo dev to go anywhere with this.
